/* ***************************************************************************
 *
 * Copyright (c) 2020 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 *
 ****************************************************************************/

#include "TC_FUNCs.h"
#include "cmocka_custom.h"

int TEST_FUNC_iot_api(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup_teardown(TC_iot_api_device_info_load_null_parameters, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_device_info_load_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_device_info_load_internal_failure, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_device_info_load_without_firmware_version,
                                        TC_iot_api_memleak_detect_setup, TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_load_null_parameters,
                                        TC_iot_api_memleak_detect_setup, TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_load_template_parameters,
                                        TC_iot_api_memleak_detect_setup, TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_load_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_load_internal_failure,
                                        TC_iot_api_memleak_detect_setup, TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_without_mnid, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
#if defined(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP)
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_invalid_ssid_version,
                                        TC_iot_api_memleak_detect_setup, TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_invalid_onboarding_id_length_version_4,
                                        TC_iot_api_memleak_detect_setup, TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_valid_onboarding_id_length_version_5,
                                        TC_iot_api_memleak_detect_setup, TC_iot_api_memleak_detect_teardown),
#endif
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_without_dip_id, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_api_onboarding_config_without_vid, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_time_in_sec_null_parameters, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_time_in_sec_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_time_in_ms_null_parmaeters, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_time_in_ms_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_time_in_sec_by_long_null_parameters, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_time_in_sec_by_long_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_easysetup_request_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_misc_info_load_invalid_parameters, TC_iot_misc_info_dip_setup,
                                        TC_iot_misc_info_dip_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_misc_info_load_success, TC_iot_misc_info_dip_setup,
                                        TC_iot_misc_info_dip_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_misc_info_store_invalid_parameters, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_misc_info_store_success, TC_iot_misc_info_dip_setup,
                                        TC_iot_misc_info_dip_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wifi_ctrl_request_IOT_WIFI_MODE_OFF, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wifi_ctrl_request_IOT_WIFI_MODE_SCAN, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wifi_get_status_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_state_timeout_change_failure, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_state_timeout_change_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_misc_info_load_failure, TC_iot_misc_info_dip_setup,
                                        TC_iot_misc_info_dip_teardown),
        cmocka_unit_test(TC_iot_set_st_ecode_invalid_parameters),
        cmocka_unit_test_setup_teardown(TC_iot_set_st_ecode_success, TC_iot_misc_info_dip_setup,
                                        TC_iot_misc_info_dip_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_set_st_ecode_from_conn_error_success, TC_iot_misc_info_dip_setup,
                                        TC_iot_misc_info_dip_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_st_ecode_null_parameter, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_get_st_ecode_success, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wifi_ctrl_request_IOT_WIFI_MODE_STATION, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wifi_ctrl_request_failure, TC_iot_api_memleak_detect_setup,
                                        TC_iot_api_memleak_detect_teardown),
#if defined(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP)
        cmocka_unit_test_setup_teardown(TC_iot_wifi_ctrl_request_IOT_WIFI_MODE_SOFTAP, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
#endif
        cmocka_unit_test_setup_teardown(TC_iot_cleanup_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
    };
    return cmocka_run_group_tests_name("iot_api.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_capability(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup_teardown(TC_st_cap_create_attr_number_with_unit, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_create_attr_string_with_unit, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_create_attr_with_unit_and_data, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_handle_init_invalid_argument, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_handle_init_internal_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_handle_init_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_conn_set_noti_cb_null_parameters, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_conn_set_noti_cb_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_cmd_set_cb_invalid_parameters, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_cmd_set_cb_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_send_attr_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_send_attr_invalid_parameter, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_cap_sub_cb_success, TC_iot_capability_setup, TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_noti_sub_cb_rate_limit_reached_SUCCESS, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test(TC_iot_parse_noti_data_device_deleted),
        cmocka_unit_test(TC_iot_parse_noti_data_expired_jwt),
        cmocka_unit_test(TC_iot_parse_noti_data_quota_reached),
        cmocka_unit_test(TC_st_cap_create_attr_with_id_success),
        cmocka_unit_test(TC_st_cap_create_attr_with_option_null_parameter),
        cmocka_unit_test_setup_teardown(TC_st_cap_create_attr_with_option_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_create_attr_with_option_internal_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_create_attr_with_option_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_cmd_set_cb_internal_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_cap_commands_cb_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_cap_commands_cb_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_presference_updated, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_cap_call_init_cb_null_parameteer, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_cap_call_init_cb_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_send_attr_v2_null_parameter, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_send_attr_v2_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_cap_send_attr_v2_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_child_dev_cap_handle_init_null_parameters, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_child_dev_cap_handle_init_internal_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_st_child_dev_cap_handle_init_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_subscribe_child_devices_command_null_parameters, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_subscribe_child_devices_command_empty_array, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_subscribe_child_devices_command_malloc_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_subscribe_child_devices_command_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_v2_null_parameters, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_v2_missing_fields, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_v2_malloc_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_v2_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_cmd_data_v2_null_parameter, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_cmd_data_v2_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_null_parameters, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_missing_fields, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_malloc_failure, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_cmd_data_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_val_null_parameter, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_val_string_type, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_val_str_array_type, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_val_json_object_type, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_unit_null_parameter, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_unit_string_type, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_cmd_data_null_parameter, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_cmd_data_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_evt_data_null_parameter, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_free_evt_data_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_notify_child_devices_cloud_connected_null_parameters,
                                        TC_iot_capability_setup, TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_notify_child_devices_cloud_connected_empty_array,
                                        TC_iot_capability_setup, TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_notify_child_devices_cloud_connected_invalid_child_device,
                                        TC_iot_capability_setup, TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_notify_child_devices_cloud_connected_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_invalid_json, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_no_event_field, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_null_event_type, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_unknown_event_type, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_expired_jwt_no_current_time, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_quota_reached_no_limit, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_quota_reached_no_used, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_rate_limit_no_count, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_rate_limit_no_threshold, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_rate_limit_no_remaining_time, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_rate_limit_no_sequence_number, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_preference_updated_no_values, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_preference_updated_empty_values, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_updated_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_response, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_device_id, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_metadata, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_mn_id, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_serial_number, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_dip, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_dip_id, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_no_dip_major_version,
                                        TC_iot_capability_setup, TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_get_no_child_devices, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_get_no_device_id, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_get_no_mn_id, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_get_no_serial_number, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_get_no_dip, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_get_no_dip_id, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_get_no_dip_major_version, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_child_device_health_response_no_success,
                                        TC_iot_capability_setup, TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_device_created_success, TC_iot_capability_setup,
                                        TC_iot_capability_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_parse_noti_data_child_device_health_response_success,
                                        TC_iot_capability_setup, TC_iot_capability_teardown),
    };
    return cmocka_run_group_tests_name("iot_capability.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_nv_data(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_wifi_prov_data_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_wifi_prov_data_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_certificate_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_certificate_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_certificate_internal_failure, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_serial_number_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_serial_number_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_device_id_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_device_id_null_parameter, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_set_erase_device_id_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_erase_internal_failure, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_data_from_device_info_failure, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_data_from_device_info_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_prov_data_exist_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_prov_data_exist_no_prov_data, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_prov_data_exist_wifi_only, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_prov_data_exist_cloud_only, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_prov_data_exist_both_done, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_prov_data_exist_wifi_not_done, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_prov_data_exist_cloud_not_done, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_prov_data_success, TC_iot_nv_data_setup, TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_prov_data_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_prov_data_wifi_fail, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_prov_data_cloud_fail, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_prov_data_success, TC_iot_nv_data_setup, TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_prov_data_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_erase_prov_data_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_wifi_prov_data_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_wifi_prov_data_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_wifi_prov_data_empty_ssid, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_wifi_prov_data_empty_password, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_wifi_prov_data_empty_bssid, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_wifi_prov_data_invalid_security_type, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_cloud_prov_data_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_cloud_prov_data_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_cloud_prov_data_no_status, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_cloud_prov_data_status_not_done, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_cloud_prov_data_no_url, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_cloud_prov_data_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_cloud_prov_data_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_cloud_prov_data_null_url, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_cloud_prov_data_null_label, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_device_id_success, TC_iot_nv_data_setup, TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_device_id_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_misc_info_success, TC_iot_nv_data_setup, TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_misc_info_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_misc_info_not_exist, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_misc_info_success, TC_iot_nv_data_setup, TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_set_misc_info_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_static_certificate_success, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_static_certificate_null_parameters, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_nv_get_static_certificate_invalid_cert_id, TC_iot_nv_data_setup,
                                        TC_iot_nv_data_teardown),
    };
    return cmocka_run_group_tests_name("iot_nv_data.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_util(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_util_dump_mem),
        cmocka_unit_test(TC_iot_util_validate_uuid_format_null_str),
        cmocka_unit_test(TC_iot_util_validate_uuid_format_invalid_clock_seq),
        cmocka_unit_test(TC_iot_util_convert_str_uuid_success),
        cmocka_unit_test(TC_iot_util_convert_str_uuid_null_parameters),
        cmocka_unit_test(TC_iot_util_convert_str_uuid_invalid_length),
        cmocka_unit_test(TC_iot_util_convert_str_uuid_invalid_delimiters),
        cmocka_unit_test(TC_iot_util_convert_str_uuid_invalid_characters),
        cmocka_unit_test(TC_iot_util_convert_str_uuid_invalid_format),
        cmocka_unit_test(TC_iot_util_convert_str_uuid_invalid_version),
        cmocka_unit_test(TC_iot_util_convert_uuid_str_null_uuid),
        cmocka_unit_test(TC_iot_util_convert_uuid_str_null_buffer),
        cmocka_unit_test(TC_iot_util_convert_uuid_str_insufficient_buffer),
        cmocka_unit_test(TC_iot_util_convert_str_mac_success),
        cmocka_unit_test(TC_iot_util_convert_str_mac_null_parameters),
        cmocka_unit_test(TC_iot_util_convert_str_mac_invalid_length),
        cmocka_unit_test(TC_iot_util_convert_str_mac_invalid_format),
        cmocka_unit_test(TC_iot_util_convert_str_mac_invalid_characters),
        cmocka_unit_test(TC_iot_util_convert_str_mac_invalid_segment_format),
        cmocka_unit_test(TC_iot_util_convert_mac_str_null_mac),
        cmocka_unit_test(TC_iot_util_convert_mac_str_null_buffer),
        cmocka_unit_test(TC_iot_util_convert_mac_str_null_output_buffer),
        cmocka_unit_test(TC_iot_util_convert_mac_str_insufficient_buffer),
        cmocka_unit_test(TC_iot_util_convert_mac_str_success),
        cmocka_unit_test(TC_iot_util_convert_channel_freq_success),
        cmocka_unit_test(TC_iot_util_convert_freq_channel_success),
        cmocka_unit_test(TC_iot_util_url_parse_success),
        cmocka_unit_test(TC_iot_util_url_parse_negative_cases),
        cmocka_unit_test(TC_iot_util_queue_create_negative_cases),
        cmocka_unit_test(TC_iot_util_queue_delete_edge_cases),
        cmocka_unit_test(TC_iot_util_queue_send_negative_cases),
        cmocka_unit_test(TC_iot_util_queue_receive_negative_cases),
        cmocka_unit_test(TC_iot_util_generator_backoff),
        cmocka_unit_test(TC_iot_util_get_server_type_success),
        cmocka_unit_test(TC_iot_util_get_server_type_null_url),
        cmocka_unit_test(TC_iot_util_get_server_type_empty_url),
        cmocka_unit_test(TC_iot_util_get_server_type_unknown_domain),
        cmocka_unit_test(TC_iot_util_get_server_type_partial_url),
        cmocka_unit_test(TC_iot_util_get_server_type_wrong_domain),
        cmocka_unit_test(TC_iot_util_print_ssid_secure_positive),
        cmocka_unit_test(TC_iot_util_print_mac_secure_positive),
    };
    return cmocka_run_group_tests_name("iot_util.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_uuid(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_get_uuid_from_mac),
        cmocka_unit_test(TC_iot_get_uuid_from_mac_internal_failure),
        cmocka_unit_test(TC_iot_get_uuid_from_mac_null_parameter),
        cmocka_unit_test(TC_iot_get_uuid_from_mac_empty_mac),
        cmocka_unit_test(TC_iot_get_uuid_from_mac_short_mac),
        cmocka_unit_test(TC_iot_get_uuid_from_mac_long_mac),
        cmocka_unit_test(TC_iot_get_random_uuid_null_parameter),
        cmocka_unit_test(TC_iot_get_random_uuid_random_failure),
        cmocka_unit_test(TC_iot_get_random_uuid_multiple_calls),
        cmocka_unit_test(TC_iot_get_random_uuid_structure_validation),
        cmocka_unit_test(TC_iot_get_random_uuid_success),
        cmocka_unit_test(TC_iot_get_random_uuid_from_key_null_uuid),
        cmocka_unit_test(TC_iot_get_random_uuid_from_key_null_key),
        cmocka_unit_test(TC_iot_get_random_uuid_from_key_zero_length),
        cmocka_unit_test(TC_iot_get_random_uuid_from_key_large_length),
        cmocka_unit_test(TC_iot_get_random_uuid_from_key_wifi_failure),
        cmocka_unit_test(TC_iot_get_random_uuid_from_key_empty_string),
        cmocka_unit_test(TC_iot_get_random_uuid_boundary_test),
        cmocka_unit_test(TC_iot_get_random_uuid_from_mac),
        cmocka_unit_test(TC_iot_get_random_uuid_from_mac_internal_failure),
        cmocka_unit_test(TC_iot_get_random_uuid_from_mac_null_parameter),
        cmocka_unit_test(TC_iot_get_random_uuid_from_mac_wifi_failure),
        cmocka_unit_test(TC_iot_get_random_uuid_from_mac_malloc_failure),
        cmocka_unit_test(TC_iot_get_random_uuid_from_mac_invalid_mac),
        cmocka_unit_test(TC_iot_get_random_uuid_from_mac_empty_mac),
    };
    return cmocka_run_group_tests_name("iot_uuid.c", tests, NULL, NULL);
}

#if defined(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP)
int TEST_FUNC_iot_easysetup_d2d(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_easysetup_create_ssid_null_parameters),
        cmocka_unit_test_setup_teardown(TC_iot_easysetup_create_ssid_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_easysetup_request_handler_invalid_parameters,
                                        TC_iot_easysetup_common_setup, TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_easysetup_request_handler_step_deviceinfo, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test(TC_STATIC_es_deviceinfo_handler_null_parameter),
        cmocka_unit_test(TC_STATIC_es_crypto_cipher_gen_iv_success),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_deviceinfo_handler_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_keyinfo_handler_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_keyinfo_handler_success_with_y2038, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_wifiprovisioninginfo_handler_success,
                                        TC_iot_easysetup_common_setup, TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_wifiprovisioninginfo_handler_success_without_authtype,
                                        TC_iot_easysetup_common_setup, TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_wifiscaninfo_handler_invalid_parameters,
                                        TC_iot_easysetup_common_setup, TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_wifiscaninfo_handler_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirminfo_handler_null_parameters, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirminfo_handler_out_ranged_otm_feature,
                                        TC_iot_easysetup_common_setup, TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirminfo_handler_justworks_and_pin,
                                        TC_iot_easysetup_common_setup, TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirminfo_handler_qr_code, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirminfo_handler_serial_number, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirminfo_handler_button, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirm_handler_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirm_handler_invalid_pin, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirm_handler_non_pin_otm, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_confirm_handler_invalid_payload, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test_setup_teardown(TC_STATIC_es_setupcomplete_handler_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test(TC_st_conn_ownership_confirm_SUCCESS),
        cmocka_unit_test(TC_st_conn_ownership_confirm_DENY),
    };
    return cmocka_run_group_tests_name("iot_easysetup_d2d.c", tests, NULL, NULL);
}
#endif

int TEST_FUNC_iot_main()
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_st_conn_init_null_parameters),
        cmocka_unit_test(TC_st_conn_init_malloc_failure),
        cmocka_unit_test(TC_st_conn_init_wrong_onboarding_config),
        cmocka_unit_test(TC_st_conn_init_wrong_device_info),
        cmocka_unit_test(TC_st_conn_init_success),
        cmocka_unit_test(TC_st_conn_cleanup_invalid_parameters),
        cmocka_unit_test(TC_st_conn_cleanup_success),
        cmocka_unit_test(TC_easysetup_resources_create_delete_success),
        cmocka_unit_test(TC_create_easysetup_resources_pin_type_null_pin),
        cmocka_unit_test(TC_create_easysetup_resources_pin_malloc_failure),
        cmocka_unit_test(TC_con_timeout_check_null_timer),
        cmocka_unit_test(TC_con_timeout_check_timer_expired),
        cmocka_unit_test(TC_check_prov_data_validation),
        cmocka_unit_test(TC_iot_command_send_success),
        cmocka_unit_test(TC_iot_put_device_work_success),
        cmocka_unit_test(TC_st_device_init_null_parameter),
        cmocka_unit_test(TC_st_device_init_invalid_identity_method),
        cmocka_unit_test(TC_st_device_init_success),
        cmocka_unit_test(TC_st_conn_start_null_context),
        cmocka_unit_test(TC_st_conn_start_invalid_context),
        cmocka_unit_test(TC_st_conn_start_already_running),
        cmocka_unit_test(TC_st_conn_start_missing_status_cb),
        cmocka_unit_test(TC_st_conn_start_ex_null_context),
        cmocka_unit_test(TC_st_conn_start_ex_null_ext_args),
        cmocka_unit_test(TC_st_conn_start_ex_invalid_start_pt),
        cmocka_unit_test(TC_st_conn_start_ex_missing_status_cb),
        cmocka_unit_test(TC_st_info_get_null_context),
        cmocka_unit_test(TC_st_info_get_null_info_data),
        cmocka_unit_test(TC_st_info_get_invalid_info_type),
        cmocka_unit_test(TC_st_info_get_missing_broker_url),
        cmocka_unit_test(TC_st_info_get_invalid_context_missing_fields),
        cmocka_unit_test(TC_st_info_get_status_and_stat_success),
        cmocka_unit_test(TC_st_info_get_provisioned_success),
        cmocka_unit_test(TC_st_info_get_server_env_prod_ap_northeast2_success),
        cmocka_unit_test(TC_st_info_get_server_env_prod_us_east1_success),
        cmocka_unit_test(TC_st_info_get_server_env_prod_eu_west1_success),
        cmocka_unit_test(TC_st_info_get_server_env_prod_china_success),
        cmocka_unit_test(TC_st_info_get_server_env_acc_us_east2_success),
        cmocka_unit_test(TC_st_info_get_server_env_stg_us_east1_success),
        cmocka_unit_test(TC_st_info_get_server_env_stg_china_success),
        cmocka_unit_test(TC_st_info_get_server_env_dev_us_east1_success),
        cmocka_unit_test(TC_st_info_get_server_env_unknown_server_success),
        cmocka_unit_test(TC_st_change_health_period_null_context),
        cmocka_unit_test(TC_st_change_health_period_invalid_context),
        cmocka_unit_test(TC_st_change_health_period_success),
        cmocka_unit_test(TC_st_register_child_dev_invalid_context_state),
        cmocka_unit_test(TC_st_register_child_dev_null_mqtt_client),
        cmocka_unit_test(TC_st_register_child_dev_mqtt_publish_failure),
        cmocka_unit_test(TC_st_register_child_dev_success),
        cmocka_unit_test(TC_st_get_child_dev_null_context),
        cmocka_unit_test(TC_st_get_child_dev_null_mnid),
        cmocka_unit_test(TC_st_get_child_dev_null_serial_number),
        cmocka_unit_test(TC_st_get_child_dev_no_match),
        cmocka_unit_test(TC_st_get_child_dev_success),
        cmocka_unit_test(TC_st_child_dev_start_null_child_dev),
        cmocka_unit_test(TC_st_child_dev_start_success),
        cmocka_unit_test(TC_st_change_device_name_null_context),
        cmocka_unit_test(TC_st_change_device_name_null_new_name),
        cmocka_unit_test(TC_st_change_device_name_invalid_context_state),
        cmocka_unit_test(TC_st_change_device_name_null_mqtt_client),
        cmocka_unit_test(TC_st_change_device_name_name_too_long),
        cmocka_unit_test(TC_st_change_device_name_success),
        cmocka_unit_test_setup_teardown(TC_do_iot_main_command_state_update_positive, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test(TC_do_iot_main_command_cloud_registering_negative),
        cmocka_unit_test(TC_do_iot_main_command_cloud_connecting_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_rate_limit_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_dev_deleted_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_quota_reached_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_preference_updated_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_send_failed_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_jwt_expired_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_child_device_synced_positive),
        cmocka_unit_test(TC_do_iot_main_command_notification_child_device_registered_positive),
        cmocka_unit_test(TC_do_iot_main_command_system_reboot_positive),
        cmocka_unit_test(TC_do_iot_main_command_invalid_command_type_negative),
        cmocka_unit_test(TC_do_iot_main_command_invalid_state_negative),
        cmocka_unit_test(TC_check_prov_status_failure),
        cmocka_unit_test(TC_check_prov_status_dip_need_update_negative),
        cmocka_unit_test(TC_check_prov_status_success),
        cmocka_unit_test(TC_check_prov_status_device_id_present_success),
        cmocka_unit_test(TC_check_prov_status_invalid_prov_data),
        cmocka_unit_test(TC_check_prov_status_no_device_id),
        cmocka_unit_test(TC_delete_dev_card_by_usr_null_context),
        cmocka_unit_test(TC_delete_dev_card_by_usr_null_mqtt_client),
        cmocka_unit_test(TC_delete_dev_card_by_usr_not_connected),
        cmocka_unit_test(TC_delete_dev_card_by_usr_mqtt_publish_failure),
        cmocka_unit_test(TC_delete_dev_card_by_usr_success),
        cmocka_unit_test_setup_teardown(TC_do_state_updating_success, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test(TC_do_state_updating_failure),
        cmocka_unit_test(TC_do_state_updating_prov_sleep_success),
#if defined(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP)
        cmocka_unit_test(TC_do_state_updating_prov_sleep_failure),
#endif
        cmocka_unit_test(TC_do_state_updating_prov_sleep_invalid_args_failure),
        cmocka_unit_test(TC_do_state_updating_state_initialized_failure),
        cmocka_unit_test(TC_do_state_updating_state_prov_confirm_failure),
        cmocka_unit_test_setup_teardown(TC_do_state_updating_state_prov_done_failure, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test(TC_do_state_updating_prov_enter_invalid_args_failure),
        cmocka_unit_test(TC_do_state_updating_invalid_args_failure),
        cmocka_unit_test(TC_command_work_handler_null_cmd_data_N),
        cmocka_unit_test_setup_teardown(TC_command_work_handler_success_P, TC_iot_easysetup_common_setup,
                                        TC_iot_easysetup_common_teardown),
        cmocka_unit_test(TC_next_connection_retry_timeout_success_P),
        cmocka_unit_test(TC_iot_state_timeout_cb_P),
        cmocka_unit_test(TC_iot_state_timeout_cb_prov_enter_P),
        cmocka_unit_test(TC_iot_state_timeout_cb_prov_done_P),
        cmocka_unit_test(TC_get_device_preference_null_mqtt_client_N),
        cmocka_unit_test(TC_get_device_preference_success_P),
    };
    return cmocka_run_group_tests_name("iot_main.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_mqtt_client()
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_st_mqtt_create_success),          cmocka_unit_test(TC_st_mqtt_create_failure),
        cmocka_unit_test(TC_st_mqtt_connect_with_connack_rc), cmocka_unit_test(TC_st_mqtt_disconnect_success),
        cmocka_unit_test(TC_st_mqtt_publish_success),
    };
    return cmocka_run_group_tests_name("iot_mqtt_client.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_common(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_security_init_malloc_failure),
        cmocka_unit_test(TC_iot_security_init_success),
        cmocka_unit_test(TC_iot_security_deinit_null_parameters),
        cmocka_unit_test(TC_iot_security_deinit_success),
        cmocka_unit_test(TC_iot_security_check_context_is_valid_null_parameters),
        cmocka_unit_test(TC_iot_security_check_context_is_valid_success),
        cmocka_unit_test(TC_iot_security_check_backend_funcs_entry_is_valid_failure),
        cmocka_unit_test(TC_iot_security_check_backend_funcs_entry_is_valid_success),
    };
    return cmocka_run_group_tests_name("iot_security_common.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_crypto(void)
{
    const struct CMUnitTest tests[] = {
        // pk
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_init_null_parameters, TC_iot_security_pk_init_setup,
                                        TC_iot_security_pk_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_init_malloc_failure, TC_iot_security_pk_init_setup,
                                        TC_iot_security_pk_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_init_success, TC_iot_security_pk_init_setup,
                                        TC_iot_security_pk_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_deinit_null_parameters, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_deinit_success, TC_iot_security_pk_init_setup,
                                        TC_iot_security_pk_init_teardown),
        cmocka_unit_test(TC_iot_security_pk_get_signature_len_failure),
        cmocka_unit_test(TC_iot_security_pk_get_signature_len_success),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_get_key_type_failure, TC_iot_security_pk_init_setup,
                                        TC_iot_security_pk_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_get_key_type_success, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_sign_invalid_parameters, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_sign_null_parameters, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_sign_malloc_failure, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_sign_failure, TC_iot_security_pk_init_setup,
                                        TC_iot_security_pk_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_verify_invalid_parameters, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_verify_null_parameters, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_verify_failure, TC_iot_security_pk_init_setup,
                                        TC_iot_security_pk_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_pk_success, TC_iot_security_pk_setup,
                                        TC_iot_security_pk_teardown),
        // cipher
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_init_null_parameters, TC_iot_security_cipher_init_setup,
                                        TC_iot_security_cipher_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_init_malloc_failure, TC_iot_security_cipher_init_setup,
                                        TC_iot_security_cipher_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_init_success, TC_iot_security_cipher_init_setup,
                                        TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_deinit_null_parameters, TC_iot_security_cipher_setup,
                                        TC_iot_security_cipher_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_deinit_success, TC_iot_security_cipher_setup,
                                        TC_iot_security_cipher_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_set_params_invalid_parameters,
                                        TC_iot_security_cipher_setup, TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_set_params_null_parameters, TC_iot_security_cipher_setup,
                                        TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_set_params_success, TC_iot_security_cipher_setup,
                                        TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_encrypt_invalid_parameters,
                                        TC_iot_security_cipher_setup, TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_encrypt_null_parameters,
                                        TC_iot_security_cipher_setup, TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_encrypt_malloc_failure, TC_iot_security_cipher_setup,
                                        TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_encrypt_failure, TC_iot_security_cipher_init_setup,
                                        TC_iot_security_cipher_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_decrypt_invalid_parameters,
                                        TC_iot_security_cipher_setup, TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_decrypt_null_parameters,
                                        TC_iot_security_cipher_setup, TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_decrypt_malloc_failure, TC_iot_security_cipher_setup,
                                        TC_iot_security_cipher_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_decrypt_failure, TC_iot_security_cipher_init_setup,
                                        TC_iot_security_cipher_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_cipher_aes_success, TC_iot_security_cipher_setup,
                                        TC_iot_security_cipher_teardown),
    };
    return cmocka_run_group_tests_name("iot_security_crypto.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_ecdh(void)
{
    const struct CMUnitTest tests[] = {
#if defined(CONFIG_STDK_IOT_CORE_CRYPTO_SUPPORT_ED25519)
        cmocka_unit_test(TC_iot_security_ecdh_init_null_parameters),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_init_malloc_failure, TC_iot_security_ecdh_init_setup,
                                        TC_iot_security_ecdh_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_init_success, TC_iot_security_ecdh_init_setup,
                                        TC_iot_security_ecdh_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_set_params_null_parameters, TC_iot_security_ecdh_setup,
                                        TC_iot_security_ecdh_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_set_params_invalid_parameters, TC_iot_security_ecdh_setup,
                                        TC_iot_security_ecdh_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_set_params_success, TC_iot_security_ecdh_setup,
                                        TC_iot_security_ecdh_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_compute_shared_secret_null_parameters,
                                        TC_iot_security_ecdh_setup, TC_iot_security_ecdh_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_compute_shared_secret_malloc_failure,
                                        TC_iot_security_ecdh_setup, TC_iot_security_ecdh_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_compute_shared_secret_failure,
                                        TC_iot_security_ecdh_init_setup, TC_iot_security_ecdh_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_compute_shared_secret_success, TC_iot_security_ecdh_setup,
                                        TC_iot_security_ecdh_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_and_dynamic_cipher, TC_iot_security_ecdh_setup,
                                        TC_iot_security_ecdh_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_ecdh_and_static_cipher, TC_iot_security_ecdh_setup,
                                        TC_iot_security_ecdh_teardown),
#endif
    };
    return cmocka_run_group_tests_name("iot_security_ecdh.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_manager(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_security_manager_init_null_parameters),
        cmocka_unit_test(TC_iot_security_manager_init_success),
        cmocka_unit_test(TC_iot_security_manager_deinit_null_parameters),
        cmocka_unit_test(TC_iot_security_manager_deinit_success),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_set_key_null_parameters, TC_iot_security_manager_setup,
                                        TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_set_key_invalid_parameters,
                                        TC_iot_security_manager_setup, TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_set_key_success, TC_iot_security_manager_setup,
                                        TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_key_null_parameters, TC_iot_security_manager_setup,
                                        TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_key_invalid_parameters,
                                        TC_iot_security_manager_setup, TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_key_alloc_failure, TC_iot_security_manager_setup,
                                        TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_key_success, TC_iot_security_manager_setup,
                                        TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_certificate_null_parameters,
                                        TC_iot_security_manager_setup, TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_certificate_invalid_parameters,
                                        TC_iot_security_manager_setup, TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_certificate_alloc_failure,
                                        TC_iot_security_manager_setup, TC_iot_security_manager_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_manager_get_certificate_success, TC_iot_security_manager_setup,
                                        TC_iot_security_manager_teardown),
    };
    return cmocka_run_group_tests_name("iot_security_certificate.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_storage(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_init_malloc_failure, TC_iot_security_storage_init_setup,
                                        TC_iot_security_storage_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_init_null_parameters,
                                        TC_iot_security_storage_init_setup, TC_iot_security_storage_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_init_success, TC_iot_security_storage_init_setup,
                                        TC_iot_security_storage_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_deinit_null_parameters,
                                        TC_iot_security_storage_init_setup, TC_iot_security_storage_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_deinit_success, TC_iot_security_storage_init_setup,
                                        TC_iot_security_storage_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_read_malloc_failure, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_read_null_parameters, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_read_invalid_parameters, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_read_failure, TC_iot_security_storage_init_setup,
                                        TC_iot_security_storage_init_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_read_success, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_write_null_parameters, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_write_invalid_parameters, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_write_failure, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_write_success, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_remove_null_parameters, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_remove_invalid_parameters,
                                        TC_iot_security_storage_setup, TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_remove_failure, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_security_storage_remove_success, TC_iot_security_storage_setup,
                                        TC_iot_security_storage_teardown),
    };
    return cmocka_run_group_tests_name("iot_security_storage.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_helper(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_security_base64_buffer_size),
        cmocka_unit_test(TC_iot_security_base64_invalid_parameter),
        cmocka_unit_test(TC_iot_security_base64_encode_success),
        cmocka_unit_test(TC_iot_security_base64_decode_failure),
        cmocka_unit_test(TC_iot_security_base64_decode_success),
        cmocka_unit_test(TC_iot_security_base64_encode_urlsafe_success),
        cmocka_unit_test(TC_iot_security_base64_decode_urlsafe_alloc_failure),
        cmocka_unit_test(TC_iot_security_base64_decode_urlsafe_failure),
        cmocka_unit_test(TC_iot_security_base64_decode_urlsafe_success),
        cmocka_unit_test(TC_iot_security_sha256_failure),
        cmocka_unit_test(TC_iot_security_sha256_success),
    };
    return cmocka_run_group_tests_name("iot_security_helper_xxx.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_helper_ed25519(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_security_ed25519_convert_seckey_null_parameters),
        cmocka_unit_test(TC_iot_security_ed25519_convert_seckey_success),
    };
    return cmocka_run_group_tests_name("iot_security_helper_ed25519.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_security_software_be_bsp(void)
{
    const struct CMUnitTest tests[] = {
#if defined(CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE)
        cmocka_unit_test(TC_STATIC_iot_security_be_bsp_fs_storage_id2target_invalid_parameters),
        cmocka_unit_test(TC_STATIC_iot_security_be_bsp_fs_storage_id2target_success),
        cmocka_unit_test(TC_STATIC_iot_security_be_bsp_fs_storage_id2filename_invalid_parameters),
        cmocka_unit_test(TC_STATIC_iot_security_be_bsp_fs_storage_id2filename_success),
        cmocka_unit_test(TC_iot_security_be_bsp_fs_load_malloc_failure),
        cmocka_unit_test(TC_iot_security_be_bsp_fs_load_invalid_parameters),
        cmocka_unit_test(TC_iot_security_be_bsp_fs_load_success),
        cmocka_unit_test(TC_iot_security_be_bsp_fs_store_invalid_parameters),
        cmocka_unit_test(TC_iot_security_be_bsp_fs_store_success),
        cmocka_unit_test(TC_iot_security_be_bsp_fs_remove_invalid_parameters),
        cmocka_unit_test(TC_iot_security_be_bsp_fs_remove_success),
        cmocka_unit_test(TC_iot_security_be_bsp_init_null_parameters),
        cmocka_unit_test(TC_iot_security_be_bsp_init_success),
#endif
    };
    return cmocka_run_group_tests_name("iot_security_be_bsp.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_wt(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_null_parameters, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_success, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_dipid, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_null_mnid, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_empty_mnid, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_memory_allocation_failure,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_null_wt_params, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_null_token_buf, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_null_sn, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_empty_sn, TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_consecutive_calls_success,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_empty_dipid_success,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_longest_sn,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_0,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_2,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_3,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_4,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_5,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_6,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_7,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_8,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_malloc_failure_index_9,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
        cmocka_unit_test_setup_teardown(TC_iot_wt_create_with_dipid_malloc_failure,
                                        TC_iot_wt_create_memleak_detect_setup,
                                        TC_iot_wt_create_memleak_detect_teardown),
    };
    return cmocka_run_group_tests_name("iot_wt.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_easysetup_httpd(void)
{
    // TODO : Need to mock httpd server
    // Currently there seems to be crush somewhere
    const struct CMUnitTest tests[] = {
        /*            cmocka_unit_test_setup_teardown(TC_iot_easysetup_httpd_invalid_request,
                                                    TC_iot_easysetup_httpd_setup, TC_iot_easysetup_httpd_teardown),
                    cmocka_unit_test_setup_teardown(TC_iot_easysetup_httpd_deviceinfo_success,
                                                    TC_iot_easysetup_httpd_setup, TC_iot_easysetup_httpd_teardown),
                    cmocka_unit_test_setup_teardown(TC_iot_easysetup_httpd_keyinfo_single_transfer_success,
                                                    TC_iot_easysetup_httpd_setup, TC_iot_easysetup_httpd_teardown),
                    cmocka_unit_test_setup_teardown(TC_iot_easysetup_httpd_keyinfo_separated_transfer_success,
                                                    TC_iot_easysetup_httpd_setup, TC_iot_easysetup_httpd_teardown),*/
    };
    return cmocka_run_group_tests_name("iot_easysetup_tcp_httpd.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_mqtt_subscribe_client(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_MQTTSerialize_subscribeLength_zero),
        cmocka_unit_test(TC_MQTTSerialize_subscribeLength_single_topic),
        cmocka_unit_test(TC_MQTTSerialize_subscribe_size_single_topic),
        cmocka_unit_test(TC_MQTTSerialize_subscribe_success),
        cmocka_unit_test(TC_MQTTSerialize_subscribe_multi_topic),
        cmocka_unit_test(TC_MQTTSerialize_subscribe_buffer_too_short),
        cmocka_unit_test(TC_MQTTSerialize_subscribe_zero_buffer_length),
        cmocka_unit_test(TC_MQTTSerialize_subscribe_dup_flag),
        cmocka_unit_test(TC_MQTTDeserialize_suback_success),
        cmocka_unit_test(TC_MQTTDeserialize_suback_wrong_type),
        cmocka_unit_test(TC_MQTTDeserialize_suback_truncated),
        cmocka_unit_test(TC_MQTTDeserialize_suback_too_many_qos),
        cmocka_unit_test(TC_MQTTDeserialize_suback_zero_count),
    };
    return cmocka_run_group_tests_name("iot_mqtt_subscribe_client.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_mqtt_packet(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_MQTTPacket_encode_single_byte_length),
        cmocka_unit_test(TC_MQTTPacket_encode_zero_length),
        cmocka_unit_test(TC_MQTTPacket_encode_two_byte_length),
        cmocka_unit_test(TC_MQTTPacket_encode_three_byte_length),
        cmocka_unit_test(TC_MQTTPacket_encode_four_byte_length),
        cmocka_unit_test(TC_MQTTPacket_decodeBuf_single_byte_success),
        cmocka_unit_test(TC_MQTTPacket_decodeBuf_multi_byte_success),
        cmocka_unit_test(TC_MQTTPacket_decode_getfn_failure),
        cmocka_unit_test(TC_MQTTPacket_decode_too_many_bytes),
        cmocka_unit_test(TC_MQTTPacket_len_small),
        cmocka_unit_test(TC_MQTTPacket_len_boundary_127),
        cmocka_unit_test(TC_MQTTPacket_len_two_byte_range),
        cmocka_unit_test(TC_MQTTPacket_len_three_byte_range),
        cmocka_unit_test(TC_MQTTPacket_len_four_byte_range),
        cmocka_unit_test(TC_mqtt_packet_readInt_success),
        cmocka_unit_test(TC_mqtt_packet_readChar_success),
        cmocka_unit_test(TC_mqtt_packet_writeChar_success),
        cmocka_unit_test(TC_mqtt_packet_writeInt_success),
        cmocka_unit_test(TC_mqtt_packet_writeCString_success),
        cmocka_unit_test(TC_MQTTstrlen_cstring),
        cmocka_unit_test(TC_MQTTstrlen_lenstring),
        cmocka_unit_test(TC_MQTTstrlen_empty),
        cmocka_unit_test(TC_MQTTPacket_equals_cstring_equal),
        cmocka_unit_test(TC_MQTTPacket_equals_cstring_not_equal),
        cmocka_unit_test(TC_MQTTPacket_equals_lenstring_equal),
        cmocka_unit_test(TC_MQTTPacket_equals_length_mismatch),
        cmocka_unit_test(TC_writeMQTTString_lenstring),
        cmocka_unit_test(TC_writeMQTTString_cstring),
        cmocka_unit_test(TC_writeMQTTString_empty),
        cmocka_unit_test(TC_readMQTTLenString_success),
        cmocka_unit_test(TC_readMQTTLenString_too_short_for_length),
        cmocka_unit_test(TC_readMQTTLenString_data_exceeds_end),
        cmocka_unit_test(TC_getLenStringLen_success),
        cmocka_unit_test(TC_getLenStringLen_zero),
        cmocka_unit_test(TC_MQTTPacket_msgTypesToString_connect),
        cmocka_unit_test(TC_MQTTPacket_msgTypesToString_publish),
        cmocka_unit_test(TC_MQTTPacket_msgTypesToString_all_known),
        cmocka_unit_test(TC_MQTTPacket_msgTypesToString_invalid),
        cmocka_unit_test(TC_MQTTPacket_getPacketId_puback),
        cmocka_unit_test(TC_MQTTPacket_getPacketId_publish_qos0),
        cmocka_unit_test(TC_MQTTPacket_getPacketId_publish_qos1),
        cmocka_unit_test(TC_MQTTPacket_getPacketId_unknown_type),
        cmocka_unit_test(TC_MQTTPacket_read_success),
        cmocka_unit_test(TC_MQTTPacket_read_header_getfn_failure),
        cmocka_unit_test(TC_MQTTPacket_read_buffer_too_small),
        cmocka_unit_test(TC_MQTTPacket_read_body_short),
        cmocka_unit_test(TC_MQTTPacket_readnb_success),
        cmocka_unit_test(TC_MQTTPacket_readnb_header_getfn_failure),
        cmocka_unit_test(TC_MQTTPacket_readnb_call_again_on_header),
        cmocka_unit_test(TC_MQTTPacket_readnb_buffer_too_small),
    };
    return cmocka_run_group_tests_name("iot_mqtt_packet.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_dump_log(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_dump_create_dump_state_failure),
        cmocka_unit_test(TC_iot_dump_create_dump_state_success),
        cmocka_unit_test(TC_iot_dump_log),
    };
    return cmocka_run_group_tests_name("iot_dump_log.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_log_file(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_log_file_init_success),
        cmocka_unit_test(TC_iot_log_file_init_invalid_type),
        cmocka_unit_test(TC_iot_log_file_init_ctx_alloc_failure),
        cmocka_unit_test(TC_iot_log_file_init_double_init),
        cmocka_unit_test(TC_iot_log_file_exit_success),
        cmocka_unit_test(TC_iot_log_file_exit_without_init),
        cmocka_unit_test(TC_iot_log_file_store_success),
        cmocka_unit_test(TC_iot_log_file_store_without_init),
        cmocka_unit_test(TC_iot_log_file_store_zero_size),
        cmocka_unit_test(TC_iot_log_file_store_oversize),
        cmocka_unit_test(TC_iot_log_file_store_disabled_buffer),
        cmocka_unit_test(TC_iot_log_file_sync_without_events),
        cmocka_unit_test(TC_iot_log_file_open_success),
        cmocka_unit_test(TC_iot_log_file_open_without_init),
        cmocka_unit_test(TC_iot_log_file_open_invalid_type),
        cmocka_unit_test(TC_iot_log_file_open_alloc_failure),
        cmocka_unit_test(TC_iot_log_file_open_after_overridden),
        cmocka_unit_test(TC_iot_log_file_close_success),
        cmocka_unit_test(TC_iot_log_file_close_null_handle),
        cmocka_unit_test(TC_iot_log_file_seek_success),
        cmocka_unit_test(TC_iot_log_file_seek_empty_log),
        cmocka_unit_test(TC_iot_log_file_seek_negative_offset),
        cmocka_unit_test(TC_iot_log_file_seek_invalid_type),
        cmocka_unit_test(TC_iot_log_file_read_success),
        cmocka_unit_test(TC_iot_log_file_read_null_handle),
        cmocka_unit_test(TC_iot_log_file_read_null_buffer),
        cmocka_unit_test(TC_iot_log_file_read_no_read_size_out),
        cmocka_unit_test(TC_iot_log_file_read_wrap_around),
        cmocka_unit_test(TC_iot_log_file_read_invalid_type),
        cmocka_unit_test(TC_iot_log_file_remove_success),
        cmocka_unit_test(TC_iot_log_file_remove_invalid_type),
    };
    return cmocka_run_group_tests_name("iot_log_file.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_easysetup_st_mqtt(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_SUCCESS),
        cmocka_unit_test(TC_STATIC_iot_parse_sequence_num_SUCCESS),
        cmocka_unit_test(TC_STATIC_iot_parse_sequence_num_FAILURE),
        cmocka_unit_test(TC_STATIC_iot_mqtt_registration_client_callback_SUCCESS),
        cmocka_unit_test(TC_STATIC_iot_parse_sequence_num_NULL_payload),
        cmocka_unit_test(TC_STATIC_iot_parse_sequence_num_empty_string),
        cmocka_unit_test(TC_STATIC_iot_parse_sequence_num_invalid_json),
        cmocka_unit_test(TC_STATIC_iot_parse_sequence_num_no_device_events),
        cmocka_unit_test(TC_STATIC_iot_parse_sequence_num_empty_device_events),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_json_NULL_context),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_json_no_serial),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_json_no_lookup_id),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_json_no_dip_data),
        cmocka_unit_test(TC_STATIC_iot_mqtt_registration_client_callback_NULL_context),
        cmocka_unit_test(TC_STATIC_iot_mqtt_registration_client_callback_NULL_payload),
        cmocka_unit_test(TC_STATIC_iot_mqtt_registration_client_callback_invalid_event),
        cmocka_unit_test(TC_STATIC_iot_mqtt_registration_client_callback_invalid_json),
        cmocka_unit_test(TC_STATIC_iot_mqtt_registration_client_callback_expired_jwt),
        cmocka_unit_test(TC_STATIC_iot_mqtt_registration_client_callback_error_event),
        cmocka_unit_test(TC_STATIC_check_connection_response_NULL_payload),
        cmocka_unit_test(TC_STATIC_check_connection_response_empty_payload),
        cmocka_unit_test(TC_STATIC_check_connection_response_invalid_json),
        cmocka_unit_test(TC_STATIC_check_connection_response_no_event),
        cmocka_unit_test(TC_STATIC_check_connection_response_expired_jwt_no_current_time),
        cmocka_unit_test(TC_STATIC_check_connection_response_unknown_event),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_connect_NULL_context),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_connect_NULL_username),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_connect_NULL_sign_data),
        cmocka_unit_test(TC_STATIC_iot_es_connect_NULL_context),
        cmocka_unit_test(TC_STATIC_iot_es_connect_invalid_conn_type),
        cmocka_unit_test(TC_STATIC_iot_es_connect_rate_limit),
        cmocka_unit_test(TC_STATIC_iot_es_disconnect_NULL_context),
        cmocka_unit_test(TC_STATIC_iot_es_disconnect_invalid_conn_type),
        cmocka_unit_test(TC_STATIC_iot_es_disconnect_no_mqtt_context),
        cmocka_unit_test(TC_STATIC_iot_es_set_broker_url_port_invalid_server_type),
        cmocka_unit_test(TC_STATIC_iot_es_set_broker_url_port_unsupported_server_type),
        cmocka_unit_test(TC_STATIC_iot_update_dip_NULL_context),
        cmocka_unit_test(TC_STATIC_iot_update_dip_NULL_mqtt_client),
        cmocka_unit_test(TC_STATIC_iot_update_dip_no_dip_data),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_NULL_context),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_NULL_mqtt_context),
        cmocka_unit_test(TC_STATIC_iot_es_mqtt_registration_no_serial_numbers),
    };
    return cmocka_run_group_tests_name("iot_easysetup_st_mqtt.c", tests, NULL, NULL);
}

#if defined(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP)
int TEST_FUNC_iot_easysetup_http_parser(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_es_msg_parser_VALID_GET_METHOD),
        cmocka_unit_test(TC_es_msg_parser_INVALID_GET_METHOD),
        cmocka_unit_test(TC_es_msg_parser_VALID_POST_METHOD),
        cmocka_unit_test(TC_es_msg_parser_INVALID_POST_METHOD),
    };
    return cmocka_run_group_tests_name("iot_easysetup_http_parser.c", tests, NULL, NULL);
}

int TEST_FUNC_iot_easysetup_http(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(TC_iot_easysetup_gen_post_payload_NULL_IN_PAYLOAD),
        cmocka_unit_test(TC_iot_easysetup_gen_post_payload_CMD_INVALID_STEP),
        cmocka_unit_test(TC_iot_easysetup_gen_post_payload_CMD_INVALID_SEQUENCE),
        cmocka_unit_test(TC_iot_easysetup_gen_post_payload_NULL_CONTEXT),
        cmocka_unit_test(TC_iot_easysetup_gen_post_payload_SETUPCOMPLETE_NULL_PAYLOAD),
        cmocka_unit_test(TC_iot_easysetup_gen_get_payload_CMD_INVALID_STEP),
        cmocka_unit_test(TC_iot_easysetup_gen_get_payload_CMD_INVALID_SEQUENCE),
        cmocka_unit_test(TC_iot_easysetup_gen_get_payload_NULL_CONTEXT),
        cmocka_unit_test(TC_http_msg_handler_INVALID_CMD),
        cmocka_unit_test(TC_http_msg_handler_INVALID_TYPE),
        cmocka_unit_test(TC_http_msg_handler_NULL_DATA_BUF_POST),
        cmocka_unit_test(TC_iot_easysetup_init_NULL_CONTEXT),
        cmocka_unit_test(TC_iot_easysetup_deinit_NULL_CONTEXT),
    };
    return cmocka_run_group_tests_name("iot_easysetup_http.c", tests, NULL, NULL);
}
#endif

int main(void)
{
    int err = 0;

    err += TEST_FUNC_iot_api();
    err += TEST_FUNC_iot_capability();
    err += TEST_FUNC_iot_nv_data();
    err += TEST_FUNC_iot_util();
    err += TEST_FUNC_iot_uuid();
    err += TEST_FUNC_iot_main();
    err += TEST_FUNC_iot_mqtt_client();
    err += TEST_FUNC_iot_mqtt_packet();
    err += TEST_FUNC_iot_mqtt_subscribe_client();
    err += TEST_FUNC_iot_security_common();
    err += TEST_FUNC_iot_security_crypto();
    err += TEST_FUNC_iot_security_ecdh();
    err += TEST_FUNC_iot_security_storage();
    err += TEST_FUNC_iot_security_manager();
    err += TEST_FUNC_iot_security_helper();
    err += TEST_FUNC_iot_security_helper_ed25519();
    err += TEST_FUNC_iot_security_software_be_bsp();
    err += TEST_FUNC_iot_wt();
    err += TEST_FUNC_iot_dump_log();
    err += TEST_FUNC_iot_log_file();
    err += TEST_FUNC_iot_easysetup_st_mqtt();
#if defined(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP)
    err += TEST_FUNC_iot_easysetup_httpd();
    err += TEST_FUNC_iot_easysetup_d2d();
    err += TEST_FUNC_iot_easysetup_http_parser();
    err += TEST_FUNC_iot_easysetup_http();
#endif

    return err;
}
