/* ***************************************************************************
 *
 * Copyright 2026 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 *
 ****************************************************************************/

#ifndef _IOT_CAPS_HELPER_RICE_COOKER_
#define _IOT_CAPS_HELPER_RICE_COOKER_

#include "iot_caps_helper.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
    CAP_ENUM_RICECOOKER_COOKERSTATE_VALUE_READY,
    CAP_ENUM_RICECOOKER_COOKERSTATE_VALUE_RUNNING,
    CAP_ENUM_RICECOOKER_COOKERSTATE_VALUE_SCHEDULED,
    CAP_ENUM_RICECOOKER_COOKERSTATE_VALUE_ERROR,
    CAP_ENUM_RICECOOKER_COOKERSTATE_VALUE_MAX
};

enum {
    CAP_ENUM_RICECOOKER_COOKERMODE_VALUE_COOKING,
    CAP_ENUM_RICECOOKER_COOKERMODE_VALUE_KEEPWARM,
    CAP_ENUM_RICECOOKER_COOKERMODE_VALUE_REHEATING,
    CAP_ENUM_RICECOOKER_COOKERMODE_VALUE_AUTOCLEAN,
    CAP_ENUM_RICECOOKER_COOKERMODE_VALUE_SOAKINNERPOT,
    CAP_ENUM_RICECOOKER_COOKERMODE_VALUE_MAX
};

enum {
    CAP_ENUM_RICECOOKER_SUPPORTEDCOOKERMODES_VALUE_COOKING,
    CAP_ENUM_RICECOOKER_SUPPORTEDCOOKERMODES_VALUE_KEEPWARM,
    CAP_ENUM_RICECOOKER_SUPPORTEDCOOKERMODES_VALUE_REHEATING,
    CAP_ENUM_RICECOOKER_SUPPORTEDCOOKERMODES_VALUE_AUTOCLEAN,
    CAP_ENUM_RICECOOKER_SUPPORTEDCOOKERMODES_VALUE_SOAKINNERPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDCOOKERMODES_VALUE_MAX
};

enum {
    CAP_ENUM_RICECOOKER_MENU_VALUE_STICKYPLAINRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_WELLCOOKEDPLAINRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_FROZENPLAINRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINS,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BROWNRICE100,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHBEANS,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BARLEYMIXEDGRAINRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_SUPERGRAINS,
    CAP_ENUM_RICECOOKER_MENU_VALUE_FROZENMIXEDGRAIN,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CAULDRONRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEFORGIMBAP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_PLAINQUICK,
    CAP_ENUM_RICECOOKER_MENU_VALUE_KONJACRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALAD,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINSQUICK,
    CAP_ENUM_RICECOOKER_MENU_VALUE_NUTRITIOUSRICEINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_STEAMEDDISH,
    CAP_ENUM_RICECOOKER_MENU_VALUE_NUTRITIOUSPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_SCORCHEDRICETEA,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BAKEDEGG,
    CAP_ENUM_RICECOOKER_MENU_VALUE_SOUSVIDE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_SCORCHEDRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BABYFOODSTEP1,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BABYFOODSTEP2,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BABYFOODSTEP3,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHSEASONEDVEGETABLESINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSLIM,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORVITALITY,
    CAP_ENUM_RICECOOKER_MENU_VALUE_HAEDEUL,
    CAP_ENUM_RICECOOKER_MENU_VALUE_ALCHANMI,
    CAP_ENUM_RICECOOKER_MENU_VALUE_ODAEMI,
    CAP_ENUM_RICECOOKER_MENU_VALUE_OATRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKPEARICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_QUINOARICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_LENTILBEANRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_STEAMEDSWEETPOTATO,
    CAP_ENUM_RICECOOKER_MENU_VALUE_GALBIJJIM,
    CAP_ENUM_RICECOOKER_MENU_VALUE_SAMGYETANG,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHWEBFOOTOCTOPUSANDSAUSSUREAINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHABALONEINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHTRUFFLEDBULGOGIINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHSTEAKINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHRIPEKIMCHIANDABALONEINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHBEEFANDBEANSPROUTSINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHASSORTEDMUSHROMMSINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHBRACKENANDSTEAKINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHBEEFANDASSORTEDMUSHROOMSINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_RICEWITHSPICYWEBFOOTOCTOPUSINHOTPOT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_KAMUTRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA_1CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHQUINOA,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHMILLET,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA_2CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHBARLEY,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE_1CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHOATRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE_2CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHKAMUT,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHQUINOA_1CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHQUINOA_2CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHADLAY,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN_1CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_PLAINPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN_2CUP,
    CAP_ENUM_RICECOOKER_MENU_VALUE_ABALONEPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_PINENUTPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BOILEDEGG,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKEN_SWEETPUMPKIN_CABBAGE_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKEN_ZUCCHINI_SWEETPOTATO_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BEEF_APPLE_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKEN_BOKCHOY_BANANAPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BEEF_ZUCCHINI_PEARPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BEEF_SHIITAKEMUSHROOM_EGGPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BEEF_KINGTRUMPETMUSHROOM_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKEN_BEANSPROUTS_JUJUBE_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_COD_MEAT_VITAMIN_CARROTPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKEN_SWEETPOTATO_BEET_BEETPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKEN_PINENUT_CHESTNUT_SPINACH_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BEEF_BEET_ENOKIMUSHROOM_PERILLASEEDS_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CHICKEN_CHEESE_BEET_EGGPLANT_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CODFLESH_SWEETPUMPKIN_MUNG_BEANSPROUTS_BLACKSESAME_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BEEF_CABBAGE_WHITEMUSHROOM_JUJUBE_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_POTATOCARROTPORRIDGE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_YAKBAB,
    CAP_ENUM_RICECOOKER_MENU_VALUE_STEAMEDPOTATO,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU01,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU02,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU03,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU04,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU05,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU06,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU07,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU08,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU09,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU10,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU11,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU12,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU13,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU14,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU15,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU16,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU17,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU18,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU19,
    CAP_ENUM_RICECOOKER_MENU_VALUE_CUSTOMMENU20,
    CAP_ENUM_RICECOOKER_MENU_VALUE_BABYFOOD,
    CAP_ENUM_RICECOOKER_MENU_VALUE_QUICKMEAL,
    CAP_ENUM_RICECOOKER_MENU_VALUE_NOPRESSURESTEAMING,
    CAP_ENUM_RICECOOKER_MENU_VALUE_GERMINATEDBROWNRICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_VEGETABLERICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_HIGHHEATMIXEDGRAINS,
    CAP_ENUM_RICECOOKER_MENU_VALUE_WHITERICE,
    CAP_ENUM_RICECOOKER_MENU_VALUE_GRAINS,
    CAP_ENUM_RICECOOKER_MENU_VALUE_MAX
};

enum {
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_STICKYPLAINRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_WELLCOOKEDPLAINRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_FROZENPLAINRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINS,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BROWNRICE100,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHBEANS,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BARLEYMIXEDGRAINRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_SUPERGRAINS,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_FROZENMIXEDGRAIN,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CAULDRONRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEFORGIMBAP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_PLAINQUICK,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_KONJACRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALAD,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINSQUICK,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_NUTRITIOUSRICEINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_STEAMEDDISH,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_NUTRITIOUSPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_SCORCHEDRICETEA,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BAKEDEGG,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_SOUSVIDE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_SCORCHEDRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BABYFOODSTEP1,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BABYFOODSTEP2,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BABYFOODSTEP3,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHSEASONEDVEGETABLESINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSLIM,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORVITALITY,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_HAEDEUL,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_ALCHANMI,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_ODAEMI,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_OATRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKPEARICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_QUINOARICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_LENTILBEANRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_STEAMEDSWEETPOTATO,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_GALBIJJIM,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_SAMGYETANG,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHWEBFOOTOCTOPUSANDSAUSSUREAINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHABALONEINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHTRUFFLEDBULGOGIINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHSTEAKINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHRIPEKIMCHIANDABALONEINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHBEEFANDBEANSPROUTSINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHASSORTEDMUSHROMMSINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHBRACKENANDSTEAKINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHBEEFANDASSORTEDMUSHROOMSINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_RICEWITHSPICYWEBFOOTOCTOPUSINHOTPOT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_KAMUTRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA_1CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHQUINOA,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHMILLET,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA_2CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHBARLEY,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE_1CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHOATRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE_2CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHKAMUT,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHQUINOA_1CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHQUINOA_2CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHADLAY,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN_1CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_PLAINPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN_2CUP,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_ABALONEPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_PINENUTPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BOILEDEGG,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKEN_SWEETPUMPKIN_CABBAGE_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKEN_ZUCCHINI_SWEETPOTATO_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BEEF_APPLE_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKEN_BOKCHOY_BANANAPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BEEF_ZUCCHINI_PEARPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BEEF_SHIITAKEMUSHROOM_EGGPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BEEF_KINGTRUMPETMUSHROOM_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKEN_BEANSPROUTS_JUJUBE_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_COD_MEAT_VITAMIN_CARROTPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKEN_SWEETPOTATO_BEET_BEETPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKEN_PINENUT_CHESTNUT_SPINACH_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BEEF_BEET_ENOKIMUSHROOM_PERILLASEEDS_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CHICKEN_CHEESE_BEET_EGGPLANT_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CODFLESH_SWEETPUMPKIN_MUNG_BEANSPROUTS_BLACKSESAME_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BEEF_CABBAGE_WHITEMUSHROOM_JUJUBE_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_POTATOCARROTPORRIDGE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_YAKBAB,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_STEAMEDPOTATO,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU01,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU02,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU03,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU04,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU05,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU06,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU07,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU08,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU09,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU10,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU11,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU12,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU13,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU14,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU15,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU16,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU17,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU18,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU19,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_CUSTOMMENU20,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_BABYFOOD,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_QUICKMEAL,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_NOPRESSURESTEAMING,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_GERMINATEDBROWNRICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_VEGETABLERICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_HIGHHEATMIXEDGRAINS,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_WHITERICE,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_GRAINS,
    CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MAX
};

enum {
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_STICKYPLAINRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_WELLCOOKEDPLAINRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_FROZENPLAINRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINS,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BROWNRICE100,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHBEANS,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BARLEYMIXEDGRAINRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_SUPERGRAINS,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_FROZENMIXEDGRAIN,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CAULDRONRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEFORGIMBAP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_PLAINQUICK,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_KONJACRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALAD,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINSQUICK,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_NUTRITIOUSRICEINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_STEAMEDDISH,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_NUTRITIOUSPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_SCORCHEDRICETEA,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BAKEDEGG,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_SOUSVIDE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_SCORCHEDRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BABYFOODSTEP1,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BABYFOODSTEP2,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BABYFOODSTEP3,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHSEASONEDVEGETABLESINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSLIM,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORVITALITY,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_HAEDEUL,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_ALCHANMI,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_ODAEMI,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_OATRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKPEARICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_QUINOARICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_LENTILBEANRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_STEAMEDSWEETPOTATO,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_GALBIJJIM,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_SAMGYETANG,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHWEBFOOTOCTOPUSANDSAUSSUREAINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHABALONEINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHTRUFFLEDBULGOGIINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHSTEAKINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHRIPEKIMCHIANDABALONEINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHBEEFANDBEANSPROUTSINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHASSORTEDMUSHROMMSINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHBRACKENANDSTEAKINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHBEEFANDASSORTEDMUSHROOMSINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_RICEWITHSPICYWEBFOOTOCTOPUSINHOTPOT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_KAMUTRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA_1CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHQUINOA,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHMILLET,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA_2CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHBARLEY,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE_1CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHOATRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE_2CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHKAMUT,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHBROWNRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHQUINOA_1CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHCHICKPEA,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHQUINOA_2CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHADLAY,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN_1CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_PLAINPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MIXEDGRAINFORSALADWITHLENTILBEAN_2CUP,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_ABALONEPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_PINENUTPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BOILEDEGG,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKEN_SWEETPUMPKIN_CABBAGE_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKEN_ZUCCHINI_SWEETPOTATO_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BEEF_APPLE_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKEN_BOKCHOY_BANANAPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BEEF_ZUCCHINI_PEARPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BEEF_SHIITAKEMUSHROOM_EGGPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BEEF_KINGTRUMPETMUSHROOM_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKEN_BEANSPROUTS_JUJUBE_STICKYRICEPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_COD_MEAT_VITAMIN_CARROTPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKEN_SWEETPOTATO_BEET_BEETPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKEN_PINENUT_CHESTNUT_SPINACH_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BEEF_BEET_ENOKIMUSHROOM_PERILLASEEDS_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CHICKEN_CHEESE_BEET_EGGPLANT_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CODFLESH_SWEETPUMPKIN_MUNG_BEANSPROUTS_BLACKSESAME_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BEEF_CABBAGE_WHITEMUSHROOM_JUJUBE_SOFTBOILEDRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BROCCOLIPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_POTATOCARROTPORRIDGE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_YAKBAB,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_STEAMEDPOTATO,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU01,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU02,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU03,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU04,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU05,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU06,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU07,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU08,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU09,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU10,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU11,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU12,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU13,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU14,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU15,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU16,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU17,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU18,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU19,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_CUSTOMMENU20,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_BABYFOOD,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_QUICKMEAL,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_NOPRESSURESTEAMING,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_GERMINATEDBROWNRICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_VEGETABLERICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_HIGHHEATMIXEDGRAINS,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_WHITERICE,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_GRAINS,
    CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MAX
};

enum {
    CAP_ENUM_RICECOOKER_EVENT_VALUE_COOKINGCOMPLETE,
    CAP_ENUM_RICECOOKER_EVENT_VALUE_KEEPWARMCOMPLETE,
    CAP_ENUM_RICECOOKER_EVENT_VALUE_REHEATINGCOMPLETE,
    CAP_ENUM_RICECOOKER_EVENT_VALUE_AUTOCLEANCOMPLETE,
    CAP_ENUM_RICECOOKER_EVENT_VALUE_SOAKINNERPOTCOMPLETE,
    CAP_ENUM_RICECOOKER_EVENT_VALUE_STEAMEMISSION,
    CAP_ENUM_RICECOOKER_EVENT_VALUE_MAX
};

enum {
    CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_COOKINGCOMPLETE,
    CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_KEEPWARMCOMPLETE,
    CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_REHEATINGCOMPLETE,
    CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_AUTOCLEANCOMPLETE,
    CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_SOAKINNERPOTCOMPLETE,
    CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_STEAMEMISSION,
    CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_MAX
};

const static struct iot_caps_riceCooker {
    const char *id;
    const struct riceCooker_attr_cookerState {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_COOKERSTATE_VALUE_MAX];
        const char *value_ready;
        const char *value_running;
        const char *value_scheduled;
        const char *value_error;
    } attr_cookerState;
    const struct riceCooker_attr_cookerMode {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_COOKERMODE_VALUE_MAX];
        const char *value_cooking;
        const char *value_keepWarm;
        const char *value_reheating;
        const char *value_autoClean;
        const char *value_soakInnerPot;
    } attr_cookerMode;
    const struct riceCooker_attr_supportedCookerModes {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_SUPPORTEDCOOKERMODES_VALUE_MAX];
        const char *value_cooking;
        const char *value_keepWarm;
        const char *value_reheating;
        const char *value_autoClean;
        const char *value_soakInnerPot;
    } attr_supportedCookerModes;
    const struct riceCooker_attr_menu {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_MENU_VALUE_MAX];
        const char *value_stickyPlainRice;
        const char *value_wellCookedPlainRice;
        const char *value_frozenPlainRice;
        const char *value_mixedGrains;
        const char *value_brownRice100;
        const char *value_riceWithBeans;
        const char *value_barleyMixedGrainRice;
        const char *value_superGrains;
        const char *value_frozenMixedGrain;
        const char *value_cauldronRice;
        const char *value_riceForGimbap;
        const char *value_plainQuick;
        const char *value_konjacRice;
        const char *value_mixedGrainForSalad;
        const char *value_mixedGrainsQuick;
        const char *value_nutritiousRiceInHotPot;
        const char *value_steamedDish;
        const char *value_nutritiousPorridge;
        const char *value_scorchedRiceTea;
        const char *value_bakedEgg;
        const char *value_sousVide;
        const char *value_scorchedRice;
        const char *value_babyFoodStep1;
        const char *value_babyFoodStep2;
        const char *value_babyFoodStep3;
        const char *value_riceWithSeasonedVegetablesInHotPot;
        const char *value_mixedGrainForSlim;
        const char *value_mixedGrainForVitality;
        const char *value_haedeul;
        const char *value_alchanmi;
        const char *value_odaemi;
        const char *value_oatRice;
        const char *value_chickpeaRice;
        const char *value_quinoaRice;
        const char *value_lentilBeanRice;
        const char *value_steamedSweetPotato;
        const char *value_galbijjim;
        const char *value_samgyetang;
        const char *value_riceWithWebfootOctopusAndSaussureaInHotPot;
        const char *value_riceWithAbaloneInHotPot;
        const char *value_riceWithTruffledBulgogiInHotPot;
        const char *value_riceWithSteakInHotPot;
        const char *value_riceWithRipeKimchiAndAbaloneInHotPot;
        const char *value_riceWithBeefAndBeanSproutsInHotPot;
        const char *value_riceWithAssortedMushrommsInHotPot;
        const char *value_riceWithBrackenAndSteakInHotPot;
        const char *value_riceWithBeefAndAssortedMushroomsInHotPot;
        const char *value_riceWithSpicyWebfootOctopusInHotPot;
        const char *value_kamutRice;
        const char *value_mixedGrainForSaladWithLentilBean;
        const char *value_mixedGrainForSaladWithChickpea_1Cup;
        const char *value_mixedGrainForSaladWithQuinoa;
        const char *value_mixedGrainForSaladWithMillet;
        const char *value_mixedGrainForSaladWithChickpea_2Cup;
        const char *value_mixedGrainForSaladWithBarley;
        const char *value_mixedGrainForSaladWithBrownRice_1Cup;
        const char *value_mixedGrainForSaladWithOatRice;
        const char *value_mixedGrainForSaladWithBrownRice_2Cup;
        const char *value_mixedGrainForSaladWithKamut;
        const char *value_mixedGrainForSaladWithBrownRice;
        const char *value_mixedGrainForSaladWithQuinoa_1Cup;
        const char *value_mixedGrainForSaladWithChickpea;
        const char *value_mixedGrainForSaladWithQuinoa_2Cup;
        const char *value_mixedGrainForSaladWithAdlay;
        const char *value_mixedGrainForSaladWithLentilBean_1Cup;
        const char *value_plainPorridge;
        const char *value_mixedGrainForSaladWithLentilBean_2Cup;
        const char *value_abalonePorridge;
        const char *value_pineNutPorridge;
        const char *value_boiledEgg;
        const char *value_chicken_SweetPumpkin_Cabbage_StickyRicePorridge;
        const char *value_chicken_Zucchini_SweetPotato_StickyRicePorridge;
        const char *value_beef_Apple_BroccoliPorridge;
        const char *value_chicken_BokChoy_BananaPorridge;
        const char *value_beef_Zucchini_PearPorridge;
        const char *value_beef_ShiitakeMushroom_EggPorridge;
        const char *value_beef_KingTrumpetMushroom_BroccoliPorridge;
        const char *value_chicken_BeanSprouts_Jujube_StickyRicePorridge;
        const char *value_cod_Meat_Vitamin_CarrotPorridge;
        const char *value_chicken_SweetPotato_Beet_BeetPorridge;
        const char *value_chicken_PineNut_Chestnut_Spinach_SoftBoiledRice;
        const char *value_beef_Beet_EnokiMushroom_PerillaSeeds_SoftBoiledRice;
        const char *value_chicken_Cheese_Beet_Eggplant_SoftBoiledRice;
        const char *value_codFlesh_SweetPumpkin_Mung_BeanSprouts_BlackSesame_SoftBoiledRice;
        const char *value_beef_Cabbage_WhiteMushroom_Jujube_SoftBoiledRice;
        const char *value_broccoliPorridge;
        const char *value_potatoCarrotPorridge;
        const char *value_yakbab;
        const char *value_steamedPotato;
        const char *value_customMenu01;
        const char *value_customMenu02;
        const char *value_customMenu03;
        const char *value_customMenu04;
        const char *value_customMenu05;
        const char *value_customMenu06;
        const char *value_customMenu07;
        const char *value_customMenu08;
        const char *value_customMenu09;
        const char *value_customMenu10;
        const char *value_customMenu11;
        const char *value_customMenu12;
        const char *value_customMenu13;
        const char *value_customMenu14;
        const char *value_customMenu15;
        const char *value_customMenu16;
        const char *value_customMenu17;
        const char *value_customMenu18;
        const char *value_customMenu19;
        const char *value_customMenu20;
        const char *value_babyFood;
        const char *value_quickMeal;
        const char *value_noPressureSteaming;
        const char *value_germinatedBrownRice;
        const char *value_vegetableRice;
        const char *value_highHeatMixedGrains;
        const char *value_whiteRice;
        const char *value_grains;
    } attr_menu;
    const struct riceCooker_attr_supportedMenus {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_SUPPORTEDMENUS_VALUE_MAX];
        const char *value_stickyPlainRice;
        const char *value_wellCookedPlainRice;
        const char *value_frozenPlainRice;
        const char *value_mixedGrains;
        const char *value_brownRice100;
        const char *value_riceWithBeans;
        const char *value_barleyMixedGrainRice;
        const char *value_superGrains;
        const char *value_frozenMixedGrain;
        const char *value_cauldronRice;
        const char *value_riceForGimbap;
        const char *value_plainQuick;
        const char *value_konjacRice;
        const char *value_mixedGrainForSalad;
        const char *value_mixedGrainsQuick;
        const char *value_nutritiousRiceInHotPot;
        const char *value_steamedDish;
        const char *value_nutritiousPorridge;
        const char *value_scorchedRiceTea;
        const char *value_bakedEgg;
        const char *value_sousVide;
        const char *value_scorchedRice;
        const char *value_babyFoodStep1;
        const char *value_babyFoodStep2;
        const char *value_babyFoodStep3;
        const char *value_riceWithSeasonedVegetablesInHotPot;
        const char *value_mixedGrainForSlim;
        const char *value_mixedGrainForVitality;
        const char *value_haedeul;
        const char *value_alchanmi;
        const char *value_odaemi;
        const char *value_oatRice;
        const char *value_chickpeaRice;
        const char *value_quinoaRice;
        const char *value_lentilBeanRice;
        const char *value_steamedSweetPotato;
        const char *value_galbijjim;
        const char *value_samgyetang;
        const char *value_riceWithWebfootOctopusAndSaussureaInHotPot;
        const char *value_riceWithAbaloneInHotPot;
        const char *value_riceWithTruffledBulgogiInHotPot;
        const char *value_riceWithSteakInHotPot;
        const char *value_riceWithRipeKimchiAndAbaloneInHotPot;
        const char *value_riceWithBeefAndBeanSproutsInHotPot;
        const char *value_riceWithAssortedMushrommsInHotPot;
        const char *value_riceWithBrackenAndSteakInHotPot;
        const char *value_riceWithBeefAndAssortedMushroomsInHotPot;
        const char *value_riceWithSpicyWebfootOctopusInHotPot;
        const char *value_kamutRice;
        const char *value_mixedGrainForSaladWithLentilBean;
        const char *value_mixedGrainForSaladWithChickpea_1Cup;
        const char *value_mixedGrainForSaladWithQuinoa;
        const char *value_mixedGrainForSaladWithMillet;
        const char *value_mixedGrainForSaladWithChickpea_2Cup;
        const char *value_mixedGrainForSaladWithBarley;
        const char *value_mixedGrainForSaladWithBrownRice_1Cup;
        const char *value_mixedGrainForSaladWithOatRice;
        const char *value_mixedGrainForSaladWithBrownRice_2Cup;
        const char *value_mixedGrainForSaladWithKamut;
        const char *value_mixedGrainForSaladWithBrownRice;
        const char *value_mixedGrainForSaladWithQuinoa_1Cup;
        const char *value_mixedGrainForSaladWithChickpea;
        const char *value_mixedGrainForSaladWithQuinoa_2Cup;
        const char *value_mixedGrainForSaladWithAdlay;
        const char *value_mixedGrainForSaladWithLentilBean_1Cup;
        const char *value_plainPorridge;
        const char *value_mixedGrainForSaladWithLentilBean_2Cup;
        const char *value_abalonePorridge;
        const char *value_pineNutPorridge;
        const char *value_boiledEgg;
        const char *value_chicken_SweetPumpkin_Cabbage_StickyRicePorridge;
        const char *value_chicken_Zucchini_SweetPotato_StickyRicePorridge;
        const char *value_beef_Apple_BroccoliPorridge;
        const char *value_chicken_BokChoy_BananaPorridge;
        const char *value_beef_Zucchini_PearPorridge;
        const char *value_beef_ShiitakeMushroom_EggPorridge;
        const char *value_beef_KingTrumpetMushroom_BroccoliPorridge;
        const char *value_chicken_BeanSprouts_Jujube_StickyRicePorridge;
        const char *value_cod_Meat_Vitamin_CarrotPorridge;
        const char *value_chicken_SweetPotato_Beet_BeetPorridge;
        const char *value_chicken_PineNut_Chestnut_Spinach_SoftBoiledRice;
        const char *value_beef_Beet_EnokiMushroom_PerillaSeeds_SoftBoiledRice;
        const char *value_chicken_Cheese_Beet_Eggplant_SoftBoiledRice;
        const char *value_codFlesh_SweetPumpkin_Mung_BeanSprouts_BlackSesame_SoftBoiledRice;
        const char *value_beef_Cabbage_WhiteMushroom_Jujube_SoftBoiledRice;
        const char *value_broccoliPorridge;
        const char *value_potatoCarrotPorridge;
        const char *value_yakbab;
        const char *value_steamedPotato;
        const char *value_customMenu01;
        const char *value_customMenu02;
        const char *value_customMenu03;
        const char *value_customMenu04;
        const char *value_customMenu05;
        const char *value_customMenu06;
        const char *value_customMenu07;
        const char *value_customMenu08;
        const char *value_customMenu09;
        const char *value_customMenu10;
        const char *value_customMenu11;
        const char *value_customMenu12;
        const char *value_customMenu13;
        const char *value_customMenu14;
        const char *value_customMenu15;
        const char *value_customMenu16;
        const char *value_customMenu17;
        const char *value_customMenu18;
        const char *value_customMenu19;
        const char *value_customMenu20;
        const char *value_babyFood;
        const char *value_quickMeal;
        const char *value_noPressureSteaming;
        const char *value_germinatedBrownRice;
        const char *value_vegetableRice;
        const char *value_highHeatMixedGrains;
        const char *value_whiteRice;
        const char *value_grains;
    } attr_supportedMenus;
    const struct riceCooker_attr_schedulableMenus {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_SCHEDULABLEMENUS_VALUE_MAX];
        const char *value_stickyPlainRice;
        const char *value_wellCookedPlainRice;
        const char *value_frozenPlainRice;
        const char *value_mixedGrains;
        const char *value_brownRice100;
        const char *value_riceWithBeans;
        const char *value_barleyMixedGrainRice;
        const char *value_superGrains;
        const char *value_frozenMixedGrain;
        const char *value_cauldronRice;
        const char *value_riceForGimbap;
        const char *value_plainQuick;
        const char *value_konjacRice;
        const char *value_mixedGrainForSalad;
        const char *value_mixedGrainsQuick;
        const char *value_nutritiousRiceInHotPot;
        const char *value_steamedDish;
        const char *value_nutritiousPorridge;
        const char *value_scorchedRiceTea;
        const char *value_bakedEgg;
        const char *value_sousVide;
        const char *value_scorchedRice;
        const char *value_babyFoodStep1;
        const char *value_babyFoodStep2;
        const char *value_babyFoodStep3;
        const char *value_riceWithSeasonedVegetablesInHotPot;
        const char *value_mixedGrainForSlim;
        const char *value_mixedGrainForVitality;
        const char *value_haedeul;
        const char *value_alchanmi;
        const char *value_odaemi;
        const char *value_oatRice;
        const char *value_chickpeaRice;
        const char *value_quinoaRice;
        const char *value_lentilBeanRice;
        const char *value_steamedSweetPotato;
        const char *value_galbijjim;
        const char *value_samgyetang;
        const char *value_riceWithWebfootOctopusAndSaussureaInHotPot;
        const char *value_riceWithAbaloneInHotPot;
        const char *value_riceWithTruffledBulgogiInHotPot;
        const char *value_riceWithSteakInHotPot;
        const char *value_riceWithRipeKimchiAndAbaloneInHotPot;
        const char *value_riceWithBeefAndBeanSproutsInHotPot;
        const char *value_riceWithAssortedMushrommsInHotPot;
        const char *value_riceWithBrackenAndSteakInHotPot;
        const char *value_riceWithBeefAndAssortedMushroomsInHotPot;
        const char *value_riceWithSpicyWebfootOctopusInHotPot;
        const char *value_kamutRice;
        const char *value_mixedGrainForSaladWithLentilBean;
        const char *value_mixedGrainForSaladWithChickpea_1Cup;
        const char *value_mixedGrainForSaladWithQuinoa;
        const char *value_mixedGrainForSaladWithMillet;
        const char *value_mixedGrainForSaladWithChickpea_2Cup;
        const char *value_mixedGrainForSaladWithBarley;
        const char *value_mixedGrainForSaladWithBrownRice_1Cup;
        const char *value_mixedGrainForSaladWithOatRice;
        const char *value_mixedGrainForSaladWithBrownRice_2Cup;
        const char *value_mixedGrainForSaladWithKamut;
        const char *value_mixedGrainForSaladWithBrownRice;
        const char *value_mixedGrainForSaladWithQuinoa_1Cup;
        const char *value_mixedGrainForSaladWithChickpea;
        const char *value_mixedGrainForSaladWithQuinoa_2Cup;
        const char *value_mixedGrainForSaladWithAdlay;
        const char *value_mixedGrainForSaladWithLentilBean_1Cup;
        const char *value_plainPorridge;
        const char *value_mixedGrainForSaladWithLentilBean_2Cup;
        const char *value_abalonePorridge;
        const char *value_pineNutPorridge;
        const char *value_boiledEgg;
        const char *value_chicken_SweetPumpkin_Cabbage_StickyRicePorridge;
        const char *value_chicken_Zucchini_SweetPotato_StickyRicePorridge;
        const char *value_beef_Apple_BroccoliPorridge;
        const char *value_chicken_BokChoy_BananaPorridge;
        const char *value_beef_Zucchini_PearPorridge;
        const char *value_beef_ShiitakeMushroom_EggPorridge;
        const char *value_beef_KingTrumpetMushroom_BroccoliPorridge;
        const char *value_chicken_BeanSprouts_Jujube_StickyRicePorridge;
        const char *value_cod_Meat_Vitamin_CarrotPorridge;
        const char *value_chicken_SweetPotato_Beet_BeetPorridge;
        const char *value_chicken_PineNut_Chestnut_Spinach_SoftBoiledRice;
        const char *value_beef_Beet_EnokiMushroom_PerillaSeeds_SoftBoiledRice;
        const char *value_chicken_Cheese_Beet_Eggplant_SoftBoiledRice;
        const char *value_codFlesh_SweetPumpkin_Mung_BeanSprouts_BlackSesame_SoftBoiledRice;
        const char *value_beef_Cabbage_WhiteMushroom_Jujube_SoftBoiledRice;
        const char *value_broccoliPorridge;
        const char *value_potatoCarrotPorridge;
        const char *value_yakbab;
        const char *value_steamedPotato;
        const char *value_customMenu01;
        const char *value_customMenu02;
        const char *value_customMenu03;
        const char *value_customMenu04;
        const char *value_customMenu05;
        const char *value_customMenu06;
        const char *value_customMenu07;
        const char *value_customMenu08;
        const char *value_customMenu09;
        const char *value_customMenu10;
        const char *value_customMenu11;
        const char *value_customMenu12;
        const char *value_customMenu13;
        const char *value_customMenu14;
        const char *value_customMenu15;
        const char *value_customMenu16;
        const char *value_customMenu17;
        const char *value_customMenu18;
        const char *value_customMenu19;
        const char *value_customMenu20;
        const char *value_babyFood;
        const char *value_quickMeal;
        const char *value_noPressureSteaming;
        const char *value_germinatedBrownRice;
        const char *value_vegetableRice;
        const char *value_highHeatMixedGrains;
        const char *value_whiteRice;
        const char *value_grains;
    } attr_schedulableMenus;
    const struct riceCooker_attr_completionTime {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
    } attr_completionTime;
    const struct riceCooker_attr_startTime {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
    } attr_startTime;
    const struct riceCooker_attr_event {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_EVENT_VALUE_MAX];
        const char *value_cookingComplete;
        const char *value_keepWarmComplete;
        const char *value_reheatingComplete;
        const char *value_autoCleanComplete;
        const char *value_soakInnerPotComplete;
        const char *value_steamEmission;
    } attr_event;
    const struct riceCooker_attr_supportedEvents {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
        const char *values[CAP_ENUM_RICECOOKER_SUPPORTEDEVENTS_VALUE_MAX];
        const char *value_cookingComplete;
        const char *value_keepWarmComplete;
        const char *value_reheatingComplete;
        const char *value_autoCleanComplete;
        const char *value_soakInnerPotComplete;
        const char *value_steamEmission;
    } attr_supportedEvents;
    const struct riceCooker_attr_schedulingEnabled {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
    } attr_schedulingEnabled;
    const struct riceCooker_attr_scheduledTime {
        const char *name;
        const unsigned char property;
        const unsigned char valueType;
    } attr_scheduledTime;
    const struct riceCooker_cmd_startCooking {
        const char *name;
    } cmd_startCooking;
    const struct riceCooker_cmd_setMode {
        const char *name;
    } cmd_setMode;
    const struct riceCooker_cmd_stop {
        const char *name;
    } cmd_stop;
    const struct riceCooker_cmd_scheduleCooking {
        const char *name;
    } cmd_scheduleCooking;
} caps_helper_riceCooker = {
    .id = "riceCooker",
    .attr_cookerState =
        {
            .name = "cookerState",
            .property = 0,
            .valueType = VALUE_TYPE_STRING,
            .values = {"ready", "running", "scheduled", "error"},
            .value_ready = "ready",
            .value_running = "running",
            .value_scheduled = "scheduled",
            .value_error = "error",
        },
    .attr_cookerMode =
        {
            .name = "cookerMode",
            .property = 0,
            .valueType = VALUE_TYPE_STRING,
            .values = {"cooking", "keepWarm", "reheating", "autoClean", "soakInnerPot"},
            .value_cooking = "cooking",
            .value_keepWarm = "keepWarm",
            .value_reheating = "reheating",
            .value_autoClean = "autoClean",
            .value_soakInnerPot = "soakInnerPot",
        },
    .attr_supportedCookerModes =
        {
            .name = "supportedCookerModes",
            .property = ATTR_SET_VALUE_ARRAY,
            .valueType = VALUE_TYPE_STRING,
            .values = {"cooking", "keepWarm", "reheating", "autoClean", "soakInnerPot"},
            .value_cooking = "cooking",
            .value_keepWarm = "keepWarm",
            .value_reheating = "reheating",
            .value_autoClean = "autoClean",
            .value_soakInnerPot = "soakInnerPot",
        },
    .attr_menu =
        {
            .name = "menu",
            .property = ATTR_SET_VALUE_REQUIRED,
            .valueType = VALUE_TYPE_STRING,
            .values = {"stickyPlainRice",
                       "wellCookedPlainRice",
                       "frozenPlainRice",
                       "mixedGrains",
                       "brownRice100",
                       "riceWithBeans",
                       "barleyMixedGrainRice",
                       "superGrains",
                       "frozenMixedGrain",
                       "cauldronRice",
                       "riceForGimbap",
                       "plainQuick",
                       "konjacRice",
                       "mixedGrainForSalad",
                       "mixedGrainsQuick",
                       "nutritiousRiceInHotPot",
                       "steamedDish",
                       "nutritiousPorridge",
                       "scorchedRiceTea",
                       "bakedEgg",
                       "sousVide",
                       "scorchedRice",
                       "babyFoodStep1",
                       "babyFoodStep2",
                       "babyFoodStep3",
                       "riceWithSeasonedVegetablesInHotPot",
                       "mixedGrainForSlim",
                       "mixedGrainForVitality",
                       "haedeul",
                       "alchanmi",
                       "odaemi",
                       "oatRice",
                       "chickpeaRice",
                       "quinoaRice",
                       "lentilBeanRice",
                       "steamedSweetPotato",
                       "galbijjim",
                       "samgyetang",
                       "riceWithWebfootOctopusAndSaussureaInHotPot",
                       "riceWithAbaloneInHotPot",
                       "riceWithTruffledBulgogiInHotPot",
                       "riceWithSteakInHotPot",
                       "riceWithRipeKimchiAndAbaloneInHotPot",
                       "riceWithBeefAndBeanSproutsInHotPot",
                       "riceWithAssortedMushrommsInHotPot",
                       "riceWithBrackenAndSteakInHotPot",
                       "riceWithBeefAndAssortedMushroomsInHotPot",
                       "riceWithSpicyWebfootOctopusInHotPot",
                       "kamutRice",
                       "mixedGrainForSaladWithLentilBean",
                       "mixedGrainForSaladWithChickpea(1Cup)",
                       "mixedGrainForSaladWithQuinoa",
                       "mixedGrainForSaladWithMillet",
                       "mixedGrainForSaladWithChickpea(2Cup)",
                       "mixedGrainForSaladWithBarley",
                       "mixedGrainForSaladWithBrownRice(1Cup)",
                       "mixedGrainForSaladWithOatRice",
                       "mixedGrainForSaladWithBrownRice(2Cup)",
                       "mixedGrainForSaladWithKamut",
                       "mixedGrainForSaladWithBrownRice",
                       "mixedGrainForSaladWithQuinoa(1Cup)",
                       "mixedGrainForSaladWithChickpea",
                       "mixedGrainForSaladWithQuinoa(2Cup)",
                       "mixedGrainForSaladWithAdlay",
                       "mixedGrainForSaladWithLentilBean(1Cup)",
                       "plainPorridge",
                       "mixedGrainForSaladWithLentilBean(2Cup)",
                       "abalonePorridge",
                       "pineNutPorridge",
                       "boiledEgg",
                       "chicken,SweetPumpkin,Cabbage,StickyRicePorridge",
                       "chicken,Zucchini,SweetPotato,StickyRicePorridge",
                       "beef,Apple,BroccoliPorridge",
                       "chicken,BokChoy,BananaPorridge",
                       "beef,Zucchini,PearPorridge",
                       "beef,ShiitakeMushroom,EggPorridge",
                       "beef,KingTrumpetMushroom,BroccoliPorridge",
                       "chicken,BeanSprouts,Jujube,StickyRicePorridge",
                       "cod-Meat,Vitamin,CarrotPorridge",
                       "chicken,SweetPotato,Beet,BeetPorridge",
                       "chicken,PineNut,Chestnut,Spinach,SoftBoiledRice",
                       "beef,Beet,EnokiMushroom,PerillaSeeds,SoftBoiledRice",
                       "chicken,Cheese,Beet,Eggplant,SoftBoiledRice",
                       "codFlesh,SweetPumpkin,Mung-BeanSprouts,BlackSesame,SoftBoiledRice",
                       "beef,Cabbage,WhiteMushroom,Jujube,SoftBoiledRice",
                       "broccoliPorridge",
                       "potatoCarrotPorridge",
                       "yakbab",
                       "steamedPotato",
                       "customMenu01",
                       "customMenu02",
                       "customMenu03",
                       "customMenu04",
                       "customMenu05",
                       "customMenu06",
                       "customMenu07",
                       "customMenu08",
                       "customMenu09",
                       "customMenu10",
                       "customMenu11",
                       "customMenu12",
                       "customMenu13",
                       "customMenu14",
                       "customMenu15",
                       "customMenu16",
                       "customMenu17",
                       "customMenu18",
                       "customMenu19",
                       "customMenu20",
                       "babyFood",
                       "quickMeal",
                       "noPressureSteaming",
                       "germinatedBrownRice",
                       "vegetableRice",
                       "highHeatMixedGrains",
                       "whiteRice",
                       "grains"},
            .value_stickyPlainRice = "stickyPlainRice",
            .value_wellCookedPlainRice = "wellCookedPlainRice",
            .value_frozenPlainRice = "frozenPlainRice",
            .value_mixedGrains = "mixedGrains",
            .value_brownRice100 = "brownRice100",
            .value_riceWithBeans = "riceWithBeans",
            .value_barleyMixedGrainRice = "barleyMixedGrainRice",
            .value_superGrains = "superGrains",
            .value_frozenMixedGrain = "frozenMixedGrain",
            .value_cauldronRice = "cauldronRice",
            .value_riceForGimbap = "riceForGimbap",
            .value_plainQuick = "plainQuick",
            .value_konjacRice = "konjacRice",
            .value_mixedGrainForSalad = "mixedGrainForSalad",
            .value_mixedGrainsQuick = "mixedGrainsQuick",
            .value_nutritiousRiceInHotPot = "nutritiousRiceInHotPot",
            .value_steamedDish = "steamedDish",
            .value_nutritiousPorridge = "nutritiousPorridge",
            .value_scorchedRiceTea = "scorchedRiceTea",
            .value_bakedEgg = "bakedEgg",
            .value_sousVide = "sousVide",
            .value_scorchedRice = "scorchedRice",
            .value_babyFoodStep1 = "babyFoodStep1",
            .value_babyFoodStep2 = "babyFoodStep2",
            .value_babyFoodStep3 = "babyFoodStep3",
            .value_riceWithSeasonedVegetablesInHotPot = "riceWithSeasonedVegetablesInHotPot",
            .value_mixedGrainForSlim = "mixedGrainForSlim",
            .value_mixedGrainForVitality = "mixedGrainForVitality",
            .value_haedeul = "haedeul",
            .value_alchanmi = "alchanmi",
            .value_odaemi = "odaemi",
            .value_oatRice = "oatRice",
            .value_chickpeaRice = "chickpeaRice",
            .value_quinoaRice = "quinoaRice",
            .value_lentilBeanRice = "lentilBeanRice",
            .value_steamedSweetPotato = "steamedSweetPotato",
            .value_galbijjim = "galbijjim",
            .value_samgyetang = "samgyetang",
            .value_riceWithWebfootOctopusAndSaussureaInHotPot = "riceWithWebfootOctopusAndSaussureaInHotPot",
            .value_riceWithAbaloneInHotPot = "riceWithAbaloneInHotPot",
            .value_riceWithTruffledBulgogiInHotPot = "riceWithTruffledBulgogiInHotPot",
            .value_riceWithSteakInHotPot = "riceWithSteakInHotPot",
            .value_riceWithRipeKimchiAndAbaloneInHotPot = "riceWithRipeKimchiAndAbaloneInHotPot",
            .value_riceWithBeefAndBeanSproutsInHotPot = "riceWithBeefAndBeanSproutsInHotPot",
            .value_riceWithAssortedMushrommsInHotPot = "riceWithAssortedMushrommsInHotPot",
            .value_riceWithBrackenAndSteakInHotPot = "riceWithBrackenAndSteakInHotPot",
            .value_riceWithBeefAndAssortedMushroomsInHotPot = "riceWithBeefAndAssortedMushroomsInHotPot",
            .value_riceWithSpicyWebfootOctopusInHotPot = "riceWithSpicyWebfootOctopusInHotPot",
            .value_kamutRice = "kamutRice",
            .value_mixedGrainForSaladWithLentilBean = "mixedGrainForSaladWithLentilBean",
            .value_mixedGrainForSaladWithChickpea_1Cup = "mixedGrainForSaladWithChickpea(1Cup)",
            .value_mixedGrainForSaladWithQuinoa = "mixedGrainForSaladWithQuinoa",
            .value_mixedGrainForSaladWithMillet = "mixedGrainForSaladWithMillet",
            .value_mixedGrainForSaladWithChickpea_2Cup = "mixedGrainForSaladWithChickpea(2Cup)",
            .value_mixedGrainForSaladWithBarley = "mixedGrainForSaladWithBarley",
            .value_mixedGrainForSaladWithBrownRice_1Cup = "mixedGrainForSaladWithBrownRice(1Cup)",
            .value_mixedGrainForSaladWithOatRice = "mixedGrainForSaladWithOatRice",
            .value_mixedGrainForSaladWithBrownRice_2Cup = "mixedGrainForSaladWithBrownRice(2Cup)",
            .value_mixedGrainForSaladWithKamut = "mixedGrainForSaladWithKamut",
            .value_mixedGrainForSaladWithBrownRice = "mixedGrainForSaladWithBrownRice",
            .value_mixedGrainForSaladWithQuinoa_1Cup = "mixedGrainForSaladWithQuinoa(1Cup)",
            .value_mixedGrainForSaladWithChickpea = "mixedGrainForSaladWithChickpea",
            .value_mixedGrainForSaladWithQuinoa_2Cup = "mixedGrainForSaladWithQuinoa(2Cup)",
            .value_mixedGrainForSaladWithAdlay = "mixedGrainForSaladWithAdlay",
            .value_mixedGrainForSaladWithLentilBean_1Cup = "mixedGrainForSaladWithLentilBean(1Cup)",
            .value_plainPorridge = "plainPorridge",
            .value_mixedGrainForSaladWithLentilBean_2Cup = "mixedGrainForSaladWithLentilBean(2Cup)",
            .value_abalonePorridge = "abalonePorridge",
            .value_pineNutPorridge = "pineNutPorridge",
            .value_boiledEgg = "boiledEgg",
            .value_chicken_SweetPumpkin_Cabbage_StickyRicePorridge = "chicken,SweetPumpkin,Cabbage,StickyRicePorridge",
            .value_chicken_Zucchini_SweetPotato_StickyRicePorridge = "chicken,Zucchini,SweetPotato,StickyRicePorridge",
            .value_beef_Apple_BroccoliPorridge = "beef,Apple,BroccoliPorridge",
            .value_chicken_BokChoy_BananaPorridge = "chicken,BokChoy,BananaPorridge",
            .value_beef_Zucchini_PearPorridge = "beef,Zucchini,PearPorridge",
            .value_beef_ShiitakeMushroom_EggPorridge = "beef,ShiitakeMushroom,EggPorridge",
            .value_beef_KingTrumpetMushroom_BroccoliPorridge = "beef,KingTrumpetMushroom,BroccoliPorridge",
            .value_chicken_BeanSprouts_Jujube_StickyRicePorridge = "chicken,BeanSprouts,Jujube,StickyRicePorridge",
            .value_cod_Meat_Vitamin_CarrotPorridge = "cod-Meat,Vitamin,CarrotPorridge",
            .value_chicken_SweetPotato_Beet_BeetPorridge = "chicken,SweetPotato,Beet,BeetPorridge",
            .value_chicken_PineNut_Chestnut_Spinach_SoftBoiledRice = "chicken,PineNut,Chestnut,Spinach,SoftBoiledRice",
            .value_beef_Beet_EnokiMushroom_PerillaSeeds_SoftBoiledRice =
                "beef,Beet,EnokiMushroom,PerillaSeeds,SoftBoiledRice",
            .value_chicken_Cheese_Beet_Eggplant_SoftBoiledRice = "chicken,Cheese,Beet,Eggplant,SoftBoiledRice",
            .value_codFlesh_SweetPumpkin_Mung_BeanSprouts_BlackSesame_SoftBoiledRice =
                "codFlesh,SweetPumpkin,Mung-BeanSprouts,BlackSesame,SoftBoiledRice",
            .value_beef_Cabbage_WhiteMushroom_Jujube_SoftBoiledRice =
                "beef,Cabbage,WhiteMushroom,Jujube,SoftBoiledRice",
            .value_broccoliPorridge = "broccoliPorridge",
            .value_potatoCarrotPorridge = "potatoCarrotPorridge",
            .value_yakbab = "yakbab",
            .value_steamedPotato = "steamedPotato",
            .value_customMenu01 = "customMenu01",
            .value_customMenu02 = "customMenu02",
            .value_customMenu03 = "customMenu03",
            .value_customMenu04 = "customMenu04",
            .value_customMenu05 = "customMenu05",
            .value_customMenu06 = "customMenu06",
            .value_customMenu07 = "customMenu07",
            .value_customMenu08 = "customMenu08",
            .value_customMenu09 = "customMenu09",
            .value_customMenu10 = "customMenu10",
            .value_customMenu11 = "customMenu11",
            .value_customMenu12 = "customMenu12",
            .value_customMenu13 = "customMenu13",
            .value_customMenu14 = "customMenu14",
            .value_customMenu15 = "customMenu15",
            .value_customMenu16 = "customMenu16",
            .value_customMenu17 = "customMenu17",
            .value_customMenu18 = "customMenu18",
            .value_customMenu19 = "customMenu19",
            .value_customMenu20 = "customMenu20",
            .value_babyFood = "babyFood",
            .value_quickMeal = "quickMeal",
            .value_noPressureSteaming = "noPressureSteaming",
            .value_germinatedBrownRice = "germinatedBrownRice",
            .value_vegetableRice = "vegetableRice",
            .value_highHeatMixedGrains = "highHeatMixedGrains",
            .value_whiteRice = "whiteRice",
            .value_grains = "grains",
        },
    .attr_supportedMenus =
        {
            .name = "supportedMenus",
            .property = ATTR_SET_VALUE_ARRAY,
            .valueType = VALUE_TYPE_STRING,
            .values = {"stickyPlainRice",
                       "wellCookedPlainRice",
                       "frozenPlainRice",
                       "mixedGrains",
                       "brownRice100",
                       "riceWithBeans",
                       "barleyMixedGrainRice",
                       "superGrains",
                       "frozenMixedGrain",
                       "cauldronRice",
                       "riceForGimbap",
                       "plainQuick",
                       "konjacRice",
                       "mixedGrainForSalad",
                       "mixedGrainsQuick",
                       "nutritiousRiceInHotPot",
                       "steamedDish",
                       "nutritiousPorridge",
                       "scorchedRiceTea",
                       "bakedEgg",
                       "sousVide",
                       "scorchedRice",
                       "babyFoodStep1",
                       "babyFoodStep2",
                       "babyFoodStep3",
                       "riceWithSeasonedVegetablesInHotPot",
                       "mixedGrainForSlim",
                       "mixedGrainForVitality",
                       "haedeul",
                       "alchanmi",
                       "odaemi",
                       "oatRice",
                       "chickpeaRice",
                       "quinoaRice",
                       "lentilBeanRice",
                       "steamedSweetPotato",
                       "galbijjim",
                       "samgyetang",
                       "riceWithWebfootOctopusAndSaussureaInHotPot",
                       "riceWithAbaloneInHotPot",
                       "riceWithTruffledBulgogiInHotPot",
                       "riceWithSteakInHotPot",
                       "riceWithRipeKimchiAndAbaloneInHotPot",
                       "riceWithBeefAndBeanSproutsInHotPot",
                       "riceWithAssortedMushrommsInHotPot",
                       "riceWithBrackenAndSteakInHotPot",
                       "riceWithBeefAndAssortedMushroomsInHotPot",
                       "riceWithSpicyWebfootOctopusInHotPot",
                       "kamutRice",
                       "mixedGrainForSaladWithLentilBean",
                       "mixedGrainForSaladWithChickpea(1Cup)",
                       "mixedGrainForSaladWithQuinoa",
                       "mixedGrainForSaladWithMillet",
                       "mixedGrainForSaladWithChickpea(2Cup)",
                       "mixedGrainForSaladWithBarley",
                       "mixedGrainForSaladWithBrownRice(1Cup)",
                       "mixedGrainForSaladWithOatRice",
                       "mixedGrainForSaladWithBrownRice(2Cup)",
                       "mixedGrainForSaladWithKamut",
                       "mixedGrainForSaladWithBrownRice",
                       "mixedGrainForSaladWithQuinoa(1Cup)",
                       "mixedGrainForSaladWithChickpea",
                       "mixedGrainForSaladWithQuinoa(2Cup)",
                       "mixedGrainForSaladWithAdlay",
                       "mixedGrainForSaladWithLentilBean(1Cup)",
                       "plainPorridge",
                       "mixedGrainForSaladWithLentilBean(2Cup)",
                       "abalonePorridge",
                       "pineNutPorridge",
                       "boiledEgg",
                       "chicken,SweetPumpkin,Cabbage,StickyRicePorridge",
                       "chicken,Zucchini,SweetPotato,StickyRicePorridge",
                       "beef,Apple,BroccoliPorridge",
                       "chicken,BokChoy,BananaPorridge",
                       "beef,Zucchini,PearPorridge",
                       "beef,ShiitakeMushroom,EggPorridge",
                       "beef,KingTrumpetMushroom,BroccoliPorridge",
                       "chicken,BeanSprouts,Jujube,StickyRicePorridge",
                       "cod-Meat,Vitamin,CarrotPorridge",
                       "chicken,SweetPotato,Beet,BeetPorridge",
                       "chicken,PineNut,Chestnut,Spinach,SoftBoiledRice",
                       "beef,Beet,EnokiMushroom,PerillaSeeds,SoftBoiledRice",
                       "chicken,Cheese,Beet,Eggplant,SoftBoiledRice",
                       "codFlesh,SweetPumpkin,Mung-BeanSprouts,BlackSesame,SoftBoiledRice",
                       "beef,Cabbage,WhiteMushroom,Jujube,SoftBoiledRice",
                       "broccoliPorridge",
                       "potatoCarrotPorridge",
                       "yakbab",
                       "steamedPotato",
                       "customMenu01",
                       "customMenu02",
                       "customMenu03",
                       "customMenu04",
                       "customMenu05",
                       "customMenu06",
                       "customMenu07",
                       "customMenu08",
                       "customMenu09",
                       "customMenu10",
                       "customMenu11",
                       "customMenu12",
                       "customMenu13",
                       "customMenu14",
                       "customMenu15",
                       "customMenu16",
                       "customMenu17",
                       "customMenu18",
                       "customMenu19",
                       "customMenu20",
                       "babyFood",
                       "quickMeal",
                       "noPressureSteaming",
                       "germinatedBrownRice",
                       "vegetableRice",
                       "highHeatMixedGrains",
                       "whiteRice",
                       "grains"},
            .value_stickyPlainRice = "stickyPlainRice",
            .value_wellCookedPlainRice = "wellCookedPlainRice",
            .value_frozenPlainRice = "frozenPlainRice",
            .value_mixedGrains = "mixedGrains",
            .value_brownRice100 = "brownRice100",
            .value_riceWithBeans = "riceWithBeans",
            .value_barleyMixedGrainRice = "barleyMixedGrainRice",
            .value_superGrains = "superGrains",
            .value_frozenMixedGrain = "frozenMixedGrain",
            .value_cauldronRice = "cauldronRice",
            .value_riceForGimbap = "riceForGimbap",
            .value_plainQuick = "plainQuick",
            .value_konjacRice = "konjacRice",
            .value_mixedGrainForSalad = "mixedGrainForSalad",
            .value_mixedGrainsQuick = "mixedGrainsQuick",
            .value_nutritiousRiceInHotPot = "nutritiousRiceInHotPot",
            .value_steamedDish = "steamedDish",
            .value_nutritiousPorridge = "nutritiousPorridge",
            .value_scorchedRiceTea = "scorchedRiceTea",
            .value_bakedEgg = "bakedEgg",
            .value_sousVide = "sousVide",
            .value_scorchedRice = "scorchedRice",
            .value_babyFoodStep1 = "babyFoodStep1",
            .value_babyFoodStep2 = "babyFoodStep2",
            .value_babyFoodStep3 = "babyFoodStep3",
            .value_riceWithSeasonedVegetablesInHotPot = "riceWithSeasonedVegetablesInHotPot",
            .value_mixedGrainForSlim = "mixedGrainForSlim",
            .value_mixedGrainForVitality = "mixedGrainForVitality",
            .value_haedeul = "haedeul",
            .value_alchanmi = "alchanmi",
            .value_odaemi = "odaemi",
            .value_oatRice = "oatRice",
            .value_chickpeaRice = "chickpeaRice",
            .value_quinoaRice = "quinoaRice",
            .value_lentilBeanRice = "lentilBeanRice",
            .value_steamedSweetPotato = "steamedSweetPotato",
            .value_galbijjim = "galbijjim",
            .value_samgyetang = "samgyetang",
            .value_riceWithWebfootOctopusAndSaussureaInHotPot = "riceWithWebfootOctopusAndSaussureaInHotPot",
            .value_riceWithAbaloneInHotPot = "riceWithAbaloneInHotPot",
            .value_riceWithTruffledBulgogiInHotPot = "riceWithTruffledBulgogiInHotPot",
            .value_riceWithSteakInHotPot = "riceWithSteakInHotPot",
            .value_riceWithRipeKimchiAndAbaloneInHotPot = "riceWithRipeKimchiAndAbaloneInHotPot",
            .value_riceWithBeefAndBeanSproutsInHotPot = "riceWithBeefAndBeanSproutsInHotPot",
            .value_riceWithAssortedMushrommsInHotPot = "riceWithAssortedMushrommsInHotPot",
            .value_riceWithBrackenAndSteakInHotPot = "riceWithBrackenAndSteakInHotPot",
            .value_riceWithBeefAndAssortedMushroomsInHotPot = "riceWithBeefAndAssortedMushroomsInHotPot",
            .value_riceWithSpicyWebfootOctopusInHotPot = "riceWithSpicyWebfootOctopusInHotPot",
            .value_kamutRice = "kamutRice",
            .value_mixedGrainForSaladWithLentilBean = "mixedGrainForSaladWithLentilBean",
            .value_mixedGrainForSaladWithChickpea_1Cup = "mixedGrainForSaladWithChickpea(1Cup)",
            .value_mixedGrainForSaladWithQuinoa = "mixedGrainForSaladWithQuinoa",
            .value_mixedGrainForSaladWithMillet = "mixedGrainForSaladWithMillet",
            .value_mixedGrainForSaladWithChickpea_2Cup = "mixedGrainForSaladWithChickpea(2Cup)",
            .value_mixedGrainForSaladWithBarley = "mixedGrainForSaladWithBarley",
            .value_mixedGrainForSaladWithBrownRice_1Cup = "mixedGrainForSaladWithBrownRice(1Cup)",
            .value_mixedGrainForSaladWithOatRice = "mixedGrainForSaladWithOatRice",
            .value_mixedGrainForSaladWithBrownRice_2Cup = "mixedGrainForSaladWithBrownRice(2Cup)",
            .value_mixedGrainForSaladWithKamut = "mixedGrainForSaladWithKamut",
            .value_mixedGrainForSaladWithBrownRice = "mixedGrainForSaladWithBrownRice",
            .value_mixedGrainForSaladWithQuinoa_1Cup = "mixedGrainForSaladWithQuinoa(1Cup)",
            .value_mixedGrainForSaladWithChickpea = "mixedGrainForSaladWithChickpea",
            .value_mixedGrainForSaladWithQuinoa_2Cup = "mixedGrainForSaladWithQuinoa(2Cup)",
            .value_mixedGrainForSaladWithAdlay = "mixedGrainForSaladWithAdlay",
            .value_mixedGrainForSaladWithLentilBean_1Cup = "mixedGrainForSaladWithLentilBean(1Cup)",
            .value_plainPorridge = "plainPorridge",
            .value_mixedGrainForSaladWithLentilBean_2Cup = "mixedGrainForSaladWithLentilBean(2Cup)",
            .value_abalonePorridge = "abalonePorridge",
            .value_pineNutPorridge = "pineNutPorridge",
            .value_boiledEgg = "boiledEgg",
            .value_chicken_SweetPumpkin_Cabbage_StickyRicePorridge = "chicken,SweetPumpkin,Cabbage,StickyRicePorridge",
            .value_chicken_Zucchini_SweetPotato_StickyRicePorridge = "chicken,Zucchini,SweetPotato,StickyRicePorridge",
            .value_beef_Apple_BroccoliPorridge = "beef,Apple,BroccoliPorridge",
            .value_chicken_BokChoy_BananaPorridge = "chicken,BokChoy,BananaPorridge",
            .value_beef_Zucchini_PearPorridge = "beef,Zucchini,PearPorridge",
            .value_beef_ShiitakeMushroom_EggPorridge = "beef,ShiitakeMushroom,EggPorridge",
            .value_beef_KingTrumpetMushroom_BroccoliPorridge = "beef,KingTrumpetMushroom,BroccoliPorridge",
            .value_chicken_BeanSprouts_Jujube_StickyRicePorridge = "chicken,BeanSprouts,Jujube,StickyRicePorridge",
            .value_cod_Meat_Vitamin_CarrotPorridge = "cod-Meat,Vitamin,CarrotPorridge",
            .value_chicken_SweetPotato_Beet_BeetPorridge = "chicken,SweetPotato,Beet,BeetPorridge",
            .value_chicken_PineNut_Chestnut_Spinach_SoftBoiledRice = "chicken,PineNut,Chestnut,Spinach,SoftBoiledRice",
            .value_beef_Beet_EnokiMushroom_PerillaSeeds_SoftBoiledRice =
                "beef,Beet,EnokiMushroom,PerillaSeeds,SoftBoiledRice",
            .value_chicken_Cheese_Beet_Eggplant_SoftBoiledRice = "chicken,Cheese,Beet,Eggplant,SoftBoiledRice",
            .value_codFlesh_SweetPumpkin_Mung_BeanSprouts_BlackSesame_SoftBoiledRice =
                "codFlesh,SweetPumpkin,Mung-BeanSprouts,BlackSesame,SoftBoiledRice",
            .value_beef_Cabbage_WhiteMushroom_Jujube_SoftBoiledRice =
                "beef,Cabbage,WhiteMushroom,Jujube,SoftBoiledRice",
            .value_broccoliPorridge = "broccoliPorridge",
            .value_potatoCarrotPorridge = "potatoCarrotPorridge",
            .value_yakbab = "yakbab",
            .value_steamedPotato = "steamedPotato",
            .value_customMenu01 = "customMenu01",
            .value_customMenu02 = "customMenu02",
            .value_customMenu03 = "customMenu03",
            .value_customMenu04 = "customMenu04",
            .value_customMenu05 = "customMenu05",
            .value_customMenu06 = "customMenu06",
            .value_customMenu07 = "customMenu07",
            .value_customMenu08 = "customMenu08",
            .value_customMenu09 = "customMenu09",
            .value_customMenu10 = "customMenu10",
            .value_customMenu11 = "customMenu11",
            .value_customMenu12 = "customMenu12",
            .value_customMenu13 = "customMenu13",
            .value_customMenu14 = "customMenu14",
            .value_customMenu15 = "customMenu15",
            .value_customMenu16 = "customMenu16",
            .value_customMenu17 = "customMenu17",
            .value_customMenu18 = "customMenu18",
            .value_customMenu19 = "customMenu19",
            .value_customMenu20 = "customMenu20",
            .value_babyFood = "babyFood",
            .value_quickMeal = "quickMeal",
            .value_noPressureSteaming = "noPressureSteaming",
            .value_germinatedBrownRice = "germinatedBrownRice",
            .value_vegetableRice = "vegetableRice",
            .value_highHeatMixedGrains = "highHeatMixedGrains",
            .value_whiteRice = "whiteRice",
            .value_grains = "grains",
        },
    .attr_schedulableMenus =
        {
            .name = "schedulableMenus",
            .property = ATTR_SET_VALUE_ARRAY,
            .valueType = VALUE_TYPE_STRING,
            .values = {"stickyPlainRice",
                       "wellCookedPlainRice",
                       "frozenPlainRice",
                       "mixedGrains",
                       "brownRice100",
                       "riceWithBeans",
                       "barleyMixedGrainRice",
                       "superGrains",
                       "frozenMixedGrain",
                       "cauldronRice",
                       "riceForGimbap",
                       "plainQuick",
                       "konjacRice",
                       "mixedGrainForSalad",
                       "mixedGrainsQuick",
                       "nutritiousRiceInHotPot",
                       "steamedDish",
                       "nutritiousPorridge",
                       "scorchedRiceTea",
                       "bakedEgg",
                       "sousVide",
                       "scorchedRice",
                       "babyFoodStep1",
                       "babyFoodStep2",
                       "babyFoodStep3",
                       "riceWithSeasonedVegetablesInHotPot",
                       "mixedGrainForSlim",
                       "mixedGrainForVitality",
                       "haedeul",
                       "alchanmi",
                       "odaemi",
                       "oatRice",
                       "chickpeaRice",
                       "quinoaRice",
                       "lentilBeanRice",
                       "steamedSweetPotato",
                       "galbijjim",
                       "samgyetang",
                       "riceWithWebfootOctopusAndSaussureaInHotPot",
                       "riceWithAbaloneInHotPot",
                       "riceWithTruffledBulgogiInHotPot",
                       "riceWithSteakInHotPot",
                       "riceWithRipeKimchiAndAbaloneInHotPot",
                       "riceWithBeefAndBeanSproutsInHotPot",
                       "riceWithAssortedMushrommsInHotPot",
                       "riceWithBrackenAndSteakInHotPot",
                       "riceWithBeefAndAssortedMushroomsInHotPot",
                       "riceWithSpicyWebfootOctopusInHotPot",
                       "kamutRice",
                       "mixedGrainForSaladWithLentilBean",
                       "mixedGrainForSaladWithChickpea(1Cup)",
                       "mixedGrainForSaladWithQuinoa",
                       "mixedGrainForSaladWithMillet",
                       "mixedGrainForSaladWithChickpea(2Cup)",
                       "mixedGrainForSaladWithBarley",
                       "mixedGrainForSaladWithBrownRice(1Cup)",
                       "mixedGrainForSaladWithOatRice",
                       "mixedGrainForSaladWithBrownRice(2Cup)",
                       "mixedGrainForSaladWithKamut",
                       "mixedGrainForSaladWithBrownRice",
                       "mixedGrainForSaladWithQuinoa(1Cup)",
                       "mixedGrainForSaladWithChickpea",
                       "mixedGrainForSaladWithQuinoa(2Cup)",
                       "mixedGrainForSaladWithAdlay",
                       "mixedGrainForSaladWithLentilBean(1Cup)",
                       "plainPorridge",
                       "mixedGrainForSaladWithLentilBean(2Cup)",
                       "abalonePorridge",
                       "pineNutPorridge",
                       "boiledEgg",
                       "chicken,SweetPumpkin,Cabbage,StickyRicePorridge",
                       "chicken,Zucchini,SweetPotato,StickyRicePorridge",
                       "beef,Apple,BroccoliPorridge",
                       "chicken,BokChoy,BananaPorridge",
                       "beef,Zucchini,PearPorridge",
                       "beef,ShiitakeMushroom,EggPorridge",
                       "beef,KingTrumpetMushroom,BroccoliPorridge",
                       "chicken,BeanSprouts,Jujube,StickyRicePorridge",
                       "cod-Meat,Vitamin,CarrotPorridge",
                       "chicken,SweetPotato,Beet,BeetPorridge",
                       "chicken,PineNut,Chestnut,Spinach,SoftBoiledRice",
                       "beef,Beet,EnokiMushroom,PerillaSeeds,SoftBoiledRice",
                       "chicken,Cheese,Beet,Eggplant,SoftBoiledRice",
                       "codFlesh,SweetPumpkin,Mung-BeanSprouts,BlackSesame,SoftBoiledRice",
                       "beef,Cabbage,WhiteMushroom,Jujube,SoftBoiledRice",
                       "broccoliPorridge",
                       "potatoCarrotPorridge",
                       "yakbab",
                       "steamedPotato",
                       "customMenu01",
                       "customMenu02",
                       "customMenu03",
                       "customMenu04",
                       "customMenu05",
                       "customMenu06",
                       "customMenu07",
                       "customMenu08",
                       "customMenu09",
                       "customMenu10",
                       "customMenu11",
                       "customMenu12",
                       "customMenu13",
                       "customMenu14",
                       "customMenu15",
                       "customMenu16",
                       "customMenu17",
                       "customMenu18",
                       "customMenu19",
                       "customMenu20",
                       "babyFood",
                       "quickMeal",
                       "noPressureSteaming",
                       "germinatedBrownRice",
                       "vegetableRice",
                       "highHeatMixedGrains",
                       "whiteRice",
                       "grains"},
            .value_stickyPlainRice = "stickyPlainRice",
            .value_wellCookedPlainRice = "wellCookedPlainRice",
            .value_frozenPlainRice = "frozenPlainRice",
            .value_mixedGrains = "mixedGrains",
            .value_brownRice100 = "brownRice100",
            .value_riceWithBeans = "riceWithBeans",
            .value_barleyMixedGrainRice = "barleyMixedGrainRice",
            .value_superGrains = "superGrains",
            .value_frozenMixedGrain = "frozenMixedGrain",
            .value_cauldronRice = "cauldronRice",
            .value_riceForGimbap = "riceForGimbap",
            .value_plainQuick = "plainQuick",
            .value_konjacRice = "konjacRice",
            .value_mixedGrainForSalad = "mixedGrainForSalad",
            .value_mixedGrainsQuick = "mixedGrainsQuick",
            .value_nutritiousRiceInHotPot = "nutritiousRiceInHotPot",
            .value_steamedDish = "steamedDish",
            .value_nutritiousPorridge = "nutritiousPorridge",
            .value_scorchedRiceTea = "scorchedRiceTea",
            .value_bakedEgg = "bakedEgg",
            .value_sousVide = "sousVide",
            .value_scorchedRice = "scorchedRice",
            .value_babyFoodStep1 = "babyFoodStep1",
            .value_babyFoodStep2 = "babyFoodStep2",
            .value_babyFoodStep3 = "babyFoodStep3",
            .value_riceWithSeasonedVegetablesInHotPot = "riceWithSeasonedVegetablesInHotPot",
            .value_mixedGrainForSlim = "mixedGrainForSlim",
            .value_mixedGrainForVitality = "mixedGrainForVitality",
            .value_haedeul = "haedeul",
            .value_alchanmi = "alchanmi",
            .value_odaemi = "odaemi",
            .value_oatRice = "oatRice",
            .value_chickpeaRice = "chickpeaRice",
            .value_quinoaRice = "quinoaRice",
            .value_lentilBeanRice = "lentilBeanRice",
            .value_steamedSweetPotato = "steamedSweetPotato",
            .value_galbijjim = "galbijjim",
            .value_samgyetang = "samgyetang",
            .value_riceWithWebfootOctopusAndSaussureaInHotPot = "riceWithWebfootOctopusAndSaussureaInHotPot",
            .value_riceWithAbaloneInHotPot = "riceWithAbaloneInHotPot",
            .value_riceWithTruffledBulgogiInHotPot = "riceWithTruffledBulgogiInHotPot",
            .value_riceWithSteakInHotPot = "riceWithSteakInHotPot",
            .value_riceWithRipeKimchiAndAbaloneInHotPot = "riceWithRipeKimchiAndAbaloneInHotPot",
            .value_riceWithBeefAndBeanSproutsInHotPot = "riceWithBeefAndBeanSproutsInHotPot",
            .value_riceWithAssortedMushrommsInHotPot = "riceWithAssortedMushrommsInHotPot",
            .value_riceWithBrackenAndSteakInHotPot = "riceWithBrackenAndSteakInHotPot",
            .value_riceWithBeefAndAssortedMushroomsInHotPot = "riceWithBeefAndAssortedMushroomsInHotPot",
            .value_riceWithSpicyWebfootOctopusInHotPot = "riceWithSpicyWebfootOctopusInHotPot",
            .value_kamutRice = "kamutRice",
            .value_mixedGrainForSaladWithLentilBean = "mixedGrainForSaladWithLentilBean",
            .value_mixedGrainForSaladWithChickpea_1Cup = "mixedGrainForSaladWithChickpea(1Cup)",
            .value_mixedGrainForSaladWithQuinoa = "mixedGrainForSaladWithQuinoa",
            .value_mixedGrainForSaladWithMillet = "mixedGrainForSaladWithMillet",
            .value_mixedGrainForSaladWithChickpea_2Cup = "mixedGrainForSaladWithChickpea(2Cup)",
            .value_mixedGrainForSaladWithBarley = "mixedGrainForSaladWithBarley",
            .value_mixedGrainForSaladWithBrownRice_1Cup = "mixedGrainForSaladWithBrownRice(1Cup)",
            .value_mixedGrainForSaladWithOatRice = "mixedGrainForSaladWithOatRice",
            .value_mixedGrainForSaladWithBrownRice_2Cup = "mixedGrainForSaladWithBrownRice(2Cup)",
            .value_mixedGrainForSaladWithKamut = "mixedGrainForSaladWithKamut",
            .value_mixedGrainForSaladWithBrownRice = "mixedGrainForSaladWithBrownRice",
            .value_mixedGrainForSaladWithQuinoa_1Cup = "mixedGrainForSaladWithQuinoa(1Cup)",
            .value_mixedGrainForSaladWithChickpea = "mixedGrainForSaladWithChickpea",
            .value_mixedGrainForSaladWithQuinoa_2Cup = "mixedGrainForSaladWithQuinoa(2Cup)",
            .value_mixedGrainForSaladWithAdlay = "mixedGrainForSaladWithAdlay",
            .value_mixedGrainForSaladWithLentilBean_1Cup = "mixedGrainForSaladWithLentilBean(1Cup)",
            .value_plainPorridge = "plainPorridge",
            .value_mixedGrainForSaladWithLentilBean_2Cup = "mixedGrainForSaladWithLentilBean(2Cup)",
            .value_abalonePorridge = "abalonePorridge",
            .value_pineNutPorridge = "pineNutPorridge",
            .value_boiledEgg = "boiledEgg",
            .value_chicken_SweetPumpkin_Cabbage_StickyRicePorridge = "chicken,SweetPumpkin,Cabbage,StickyRicePorridge",
            .value_chicken_Zucchini_SweetPotato_StickyRicePorridge = "chicken,Zucchini,SweetPotato,StickyRicePorridge",
            .value_beef_Apple_BroccoliPorridge = "beef,Apple,BroccoliPorridge",
            .value_chicken_BokChoy_BananaPorridge = "chicken,BokChoy,BananaPorridge",
            .value_beef_Zucchini_PearPorridge = "beef,Zucchini,PearPorridge",
            .value_beef_ShiitakeMushroom_EggPorridge = "beef,ShiitakeMushroom,EggPorridge",
            .value_beef_KingTrumpetMushroom_BroccoliPorridge = "beef,KingTrumpetMushroom,BroccoliPorridge",
            .value_chicken_BeanSprouts_Jujube_StickyRicePorridge = "chicken,BeanSprouts,Jujube,StickyRicePorridge",
            .value_cod_Meat_Vitamin_CarrotPorridge = "cod-Meat,Vitamin,CarrotPorridge",
            .value_chicken_SweetPotato_Beet_BeetPorridge = "chicken,SweetPotato,Beet,BeetPorridge",
            .value_chicken_PineNut_Chestnut_Spinach_SoftBoiledRice = "chicken,PineNut,Chestnut,Spinach,SoftBoiledRice",
            .value_beef_Beet_EnokiMushroom_PerillaSeeds_SoftBoiledRice =
                "beef,Beet,EnokiMushroom,PerillaSeeds,SoftBoiledRice",
            .value_chicken_Cheese_Beet_Eggplant_SoftBoiledRice = "chicken,Cheese,Beet,Eggplant,SoftBoiledRice",
            .value_codFlesh_SweetPumpkin_Mung_BeanSprouts_BlackSesame_SoftBoiledRice =
                "codFlesh,SweetPumpkin,Mung-BeanSprouts,BlackSesame,SoftBoiledRice",
            .value_beef_Cabbage_WhiteMushroom_Jujube_SoftBoiledRice =
                "beef,Cabbage,WhiteMushroom,Jujube,SoftBoiledRice",
            .value_broccoliPorridge = "broccoliPorridge",
            .value_potatoCarrotPorridge = "potatoCarrotPorridge",
            .value_yakbab = "yakbab",
            .value_steamedPotato = "steamedPotato",
            .value_customMenu01 = "customMenu01",
            .value_customMenu02 = "customMenu02",
            .value_customMenu03 = "customMenu03",
            .value_customMenu04 = "customMenu04",
            .value_customMenu05 = "customMenu05",
            .value_customMenu06 = "customMenu06",
            .value_customMenu07 = "customMenu07",
            .value_customMenu08 = "customMenu08",
            .value_customMenu09 = "customMenu09",
            .value_customMenu10 = "customMenu10",
            .value_customMenu11 = "customMenu11",
            .value_customMenu12 = "customMenu12",
            .value_customMenu13 = "customMenu13",
            .value_customMenu14 = "customMenu14",
            .value_customMenu15 = "customMenu15",
            .value_customMenu16 = "customMenu16",
            .value_customMenu17 = "customMenu17",
            .value_customMenu18 = "customMenu18",
            .value_customMenu19 = "customMenu19",
            .value_customMenu20 = "customMenu20",
            .value_babyFood = "babyFood",
            .value_quickMeal = "quickMeal",
            .value_noPressureSteaming = "noPressureSteaming",
            .value_germinatedBrownRice = "germinatedBrownRice",
            .value_vegetableRice = "vegetableRice",
            .value_highHeatMixedGrains = "highHeatMixedGrains",
            .value_whiteRice = "whiteRice",
            .value_grains = "grains",
        },
    .attr_completionTime =
        {
            .name = "completionTime",
            .property = ATTR_SET_VALUE_REQUIRED,
            .valueType = VALUE_TYPE_STRING,
        },
    .attr_startTime =
        {
            .name = "startTime",
            .property = ATTR_SET_VALUE_REQUIRED,
            .valueType = VALUE_TYPE_STRING,
        },
    .attr_event =
        {
            .name = "event",
            .property = ATTR_SET_VALUE_REQUIRED,
            .valueType = VALUE_TYPE_STRING,
            .values = {"cookingComplete", "keepWarmComplete", "reheatingComplete", "autoCleanComplete",
                       "soakInnerPotComplete", "steamEmission"},
            .value_cookingComplete = "cookingComplete",
            .value_keepWarmComplete = "keepWarmComplete",
            .value_reheatingComplete = "reheatingComplete",
            .value_autoCleanComplete = "autoCleanComplete",
            .value_soakInnerPotComplete = "soakInnerPotComplete",
            .value_steamEmission = "steamEmission",
        },
    .attr_supportedEvents =
        {
            .name = "supportedEvents",
            .property = ATTR_SET_VALUE_ARRAY,
            .valueType = VALUE_TYPE_STRING,
            .values = {"cookingComplete", "keepWarmComplete", "reheatingComplete", "autoCleanComplete",
                       "soakInnerPotComplete", "steamEmission"},
            .value_cookingComplete = "cookingComplete",
            .value_keepWarmComplete = "keepWarmComplete",
            .value_reheatingComplete = "reheatingComplete",
            .value_autoCleanComplete = "autoCleanComplete",
            .value_soakInnerPotComplete = "soakInnerPotComplete",
            .value_steamEmission = "steamEmission",
        },
    .attr_schedulingEnabled =
        {
            .name = "schedulingEnabled",
            .property = ATTR_SET_VALUE_REQUIRED,
            .valueType = VALUE_TYPE_BOOLEAN,
        },
    .attr_scheduledTime =
        {
            .name = "scheduledTime",
            .property = ATTR_SET_VALUE_REQUIRED,
            .valueType = VALUE_TYPE_STRING,
        },
    .cmd_startCooking = {.name = "startCooking"},  // arguments: menu(string)
    .cmd_setMode = {.name = "setMode"},            // arguments: mode(string)
    .cmd_stop = {.name = "stop"},
    .cmd_scheduleCooking = {.name = "scheduleCooking"},  // arguments: time(string) menu(string)
};

#ifdef __cplusplus
}
#endif

#endif /* _IOT_CAPS_HERLPER_RICE_COOKER_ */
